# Generated by Django 2.0.8 on 2018-09-05 20:47

import django.db.models.deletion
import strategy_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unicef_rest_framework', '0006_auto_20180905_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(db_index=True)),
                ('response_ms', models.PositiveIntegerField(default=0, verbose_name='ms')),
                ('response_length', models.PositiveIntegerField(default=0, verbose_name='length')),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('remote_addr', models.GenericIPAddressField()),
                ('host', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('query_params', models.TextField(db_index=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(max_length=255)),
                ('cached', models.BooleanField(default=False)),
                ('viewset', strategy_field.fields.StrategyClassField(blank=True, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicef_rest_framework.Service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='DailyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('total', models.IntegerField(db_index=True)),
                ('cached', models.IntegerField(db_index=True)),
                ('user', models.IntegerField(db_index=True)),
                ('response_max', models.IntegerField(db_index=True)),
                ('response_min', models.IntegerField(db_index=True)),
                ('response_average', models.FloatField(db_index=True)),
                ('unique_ips', models.IntegerField(db_index=True)),
            ],
            options={
                'ordering': ('-day',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('total', models.IntegerField(db_index=True)),
                ('cached', models.IntegerField(db_index=True)),
                ('user', models.IntegerField(db_index=True)),
                ('response_max', models.IntegerField(db_index=True)),
                ('response_min', models.IntegerField(db_index=True)),
                ('response_average', models.FloatField(db_index=True)),
                ('unique_ips', models.IntegerField(db_index=True)),
            ],
            options={
                'ordering': ('-day',),
            },
        ),
        migrations.CreateModel(
            name='PathCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('total', models.IntegerField(db_index=True)),
                ('cached', models.IntegerField(db_index=True)),
                ('response_max', models.IntegerField(db_index=True)),
                ('response_min', models.IntegerField(db_index=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unicef_rest_framework.Service')),
            ],
            options={
                'ordering': ('-day',),
            },
        ),
        migrations.CreateModel(
            name='UserCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('total', models.IntegerField(db_index=True)),
                ('cached', models.IntegerField(db_index=True)),
                ('response_max', models.IntegerField(db_index=True)),
                ('response_min', models.IntegerField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-day',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='monthlycounter',
            unique_together={('day',)},
        ),
        migrations.AlterUniqueTogether(
            name='dailycounter',
            unique_together={('day',)},
        ),
        migrations.AlterUniqueTogether(
            name='usercounter',
            unique_together={('day', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='pathcounter',
            unique_together={('day', 'path')},
        ),
    ]
