# Generated by Django 2.1.3 on 2018-11-28 14:10

import django.utils.timezone
import strategy_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('response_ms', models.PositiveIntegerField(default=0, verbose_name='ms')),
                ('response_length', models.BigIntegerField(default=0, verbose_name='length')),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('host', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('query_params', models.TextField()),
                ('data', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(max_length=255)),
                ('cached', models.BooleanField(default=False)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('viewset', strategy_field.fields.StrategyClassField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Log',
                'ordering': ('-id',),
                'get_latest_by': 'requested_at',
            },
        ),
        migrations.CreateModel(
            name='DailyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('total', models.BigIntegerField(db_index=True)),
                ('cached', models.BigIntegerField(db_index=True)),
                ('response_max', models.BigIntegerField(db_index=True)),
                ('response_min', models.BigIntegerField(db_index=True)),
                ('response_average', models.FloatField(db_index=True)),
                ('users', models.IntegerField(db_index=True)),
            ],
            options={
                'ordering': ('-day',),
                'get_latest_by': 'day',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('total', models.BigIntegerField(db_index=True)),
                ('cached', models.BigIntegerField(db_index=True)),
                ('response_max', models.BigIntegerField(db_index=True)),
                ('response_min', models.BigIntegerField(db_index=True)),
                ('response_average', models.FloatField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('total', models.BigIntegerField(db_index=True)),
                ('cached', models.BigIntegerField(db_index=True)),
                ('response_max', models.BigIntegerField(db_index=True)),
                ('response_min', models.BigIntegerField(db_index=True)),
                ('response_average', models.FloatField(db_index=True)),
                ('path', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ('-day',),
            },
        ),
        migrations.CreateModel(
            name='UserCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('total', models.BigIntegerField(db_index=True)),
                ('cached', models.BigIntegerField(db_index=True)),
                ('response_max', models.BigIntegerField(db_index=True)),
                ('response_min', models.BigIntegerField(db_index=True)),
                ('response_average', models.FloatField(db_index=True)),
            ],
        ),
    ]
