# Generated by Django 2.2.5 on 2019-09-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorbylocation',
            name='location',
        ),
    ]
