# Generated by Django 2.1 on 2018-08-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMPIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('partner_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('partner_type', models.CharField(db_index=True, max_length=255, null=True)),
                ('pd_ssfa_ref', models.CharField(max_length=255, null=True)),
                ('pd_ssfa_status', models.CharField(db_index=True, max_length=50, null=True)),
                ('pd_ssfa_start_date', models.DateField(null=True)),
                ('pd_ssfa_creation_date', models.DateField(null=True)),
                ('pd_ssfa_end_date', models.DateField(null=True)),
                ('cash_contribution', models.DecimalField(decimal_places=3, help_text='UNICEF US$ Cash contribution', max_digits=20, null=True)),
                ('supply_contribution', models.DecimalField(decimal_places=3, help_text='UNICEF US$ Supply contribution', max_digits=20, null=True)),
                ('total_budget', models.DecimalField(db_index=True, decimal_places=3, help_text='Total Budget', max_digits=20, null=True)),
                ('unicef_budget', models.DecimalField(decimal_places=3, help_text='UNICEF Budget', max_digits=20, null=True)),
                ('currency', models.CharField(help_text='Currency', max_length=201, null=True)),
                ('partner_contribution', models.CharField(help_text='Partner Contribution', max_length=202, null=True)),
                ('unicef_cash', models.CharField(help_text='Unicef Cash', max_length=203, null=True)),
                ('in_kind_amount', models.CharField(help_text='In kind Amount', max_length=204, null=True)),
                ('total', models.CharField(max_length=205, null=True)),
                ('fr_numbers_against_pd_ssfa', models.TextField(help_text='FR numbers against PD / SSFA', null=True)),
                ('fr_currencies', models.CharField(help_text='FR currencies', max_length=207, null=True)),
                ('sum_of_all_fr_planned_amount', models.CharField(help_text='Sum of all FR planned amount', max_length=208, null=True)),
                ('core_value_attached', models.CharField(help_text='Core value attached', max_length=209, null=True)),
                ('partner_link', models.CharField(help_text='Partner Link', max_length=210, null=True)),
                ('intervention_link', models.CharField(help_text='Intervention Link', max_length=211, null=True)),
                ('country_id', models.IntegerField(null=True)),
                ('partner_id', models.IntegerField(null=True)),
                ('intervention_id', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
