# Generated by Django 2.1.4 on 2018-12-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaytype',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
