# Generated by Django 2.1.5 on 2019-01-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('context_code', models.CharField(blank=True, max_length=50, null=True)),
                ('assumptions', models.TextField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('means_of_verification', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster_indicator_id', models.IntegerField(blank=True, null=True)),
                ('cluster_indicator_title', models.CharField(blank=True, max_length=1024, null=True)),
                ('cluster_name', models.CharField(blank=True, max_length=512, null=True)),
                ('response_plan_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField()),
                ('is_high_frequency', models.BooleanField()),
                ('denominator_label', models.CharField(blank=True, max_length=256, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('measurement_specifications', models.TextField(blank=True, null=True)),
                ('numerator_label', models.CharField(blank=True, max_length=256, null=True)),
                ('target_denominator', models.IntegerField(blank=True, null=True)),
                ('target_numerator', models.IntegerField(blank=True, null=True)),
                ('baseline_denominator', models.IntegerField(blank=True, null=True)),
                ('baseline_numerator', models.IntegerField(blank=True, null=True)),
                ('lower_result_name', models.CharField(blank=True, max_length=500, null=True)),
                ('result_link_intervention', models.IntegerField(blank=True, null=True)),
                ('section_name', models.CharField(blank=True, max_length=45, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('display_type', models.CharField(blank=True, max_length=10, null=True)),
                ('disaggregation_name', models.CharField(max_length=255)),
                ('disaggregation_active', models.BooleanField(default=False)),
                ('location_name', models.CharField(blank=True, max_length=254, null=True)),
                ('source_disaggregation_id', models.IntegerField(blank=True, null=True)),
                ('source_location_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='famindicator',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hact',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmpindicators',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdindicator',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Intervention'),
        ),
        migrations.AddField(
            model_name='pdindicator',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='pdindicator',
            unique_together={('schema_name', 'source_id', 'source_location_id', 'source_disaggregation_id')},
        ),
    ]
