# Generated by Django 2.1.5 on 2019-01-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('schema_name', 'source_id')},
        ),
    ]
