# Generated by Django 2.1.2 on 2018-10-29 22:14

import month.models
import unicef_security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=50)),
                ('schema_name', models.CharField(db_index=True, max_length=50)),
                ('month', month.models.MonthField(verbose_name='Month Value')),
                ('total', models.IntegerField(default=0, verbose_name='Total users')),
                ('unicef', models.IntegerField(default=0, verbose_name='UNICEF uswers')),
                ('logins', models.IntegerField(default=0, verbose_name='Number of logins')),
                ('unicef_logins', models.IntegerField(default=0, verbose_name='Number of UNICEF logins')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, unicef_security.models.TimeStampedModel),
        ),
    ]
