# Generated by Django 2.0 on 2018-08-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmpindicators',
            name='business_area_code',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pmpindicators',
            name='vendor_number',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
