# Generated by Django 2.0 on 2018-08-24 20:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180823_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(null=True)),
                ('document_type', models.CharField(max_length=255, null=True)),
                ('number', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(max_length=32, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('submission_date', models.DateTimeField(null=True)),
                ('submission_date_prc', models.DateTimeField(null=True)),
                ('review_date_prc', models.DateTimeField(null=True)),
                ('prc_review_document', models.CharField(max_length=1024, null=True)),
                ('signed_by_unicef_date', models.DateTimeField(null=True)),
                ('signed_by_partner_date', models.DateTimeField(null=True)),
                ('population_focus', models.CharField(max_length=130, null=True)),
                ('partner_authorized_officer_signatory_id', models.IntegerField(null=True)),
                ('signed_pd_document', models.CharField(max_length=1024, null=True)),
                ('contingency_pd', models.NullBooleanField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('unicef_signatory_first_name', models.CharField(max_length=30, null=True)),
                ('unicef_signatory_last_name', models.CharField(max_length=30, null=True)),
                ('unicef_signatory_email', models.CharField(max_length=254, null=True)),
                ('partner_signatory_title', models.CharField(max_length=64, null=True)),
                ('partner_signatory_first_name', models.CharField(max_length=64, null=True)),
                ('partner_signatory_last_name', models.CharField(max_length=64, null=True)),
                ('partner_signatory_email', models.CharField(max_length=128, null=True)),
                ('partner_signatory_phone', models.CharField(max_length=64, null=True)),
                ('unicef_focal_point_first_name', models.CharField(max_length=30, null=True)),
                ('unicef_focal_point_last_name', models.CharField(max_length=30, null=True)),
                ('unicef_focal_point_email', models.CharField(max_length=254, null=True)),
                ('partner_focal_point_title', models.CharField(max_length=64, null=True)),
                ('partner_focal_point_first_name', models.CharField(max_length=64, null=True)),
                ('partner_focal_point_last_name', models.CharField(max_length=64, null=True)),
                ('partner_focal_point_email', models.CharField(max_length=128, null=True)),
                ('partner_focal_point_phone', models.CharField(max_length=64, null=True)),
                ('intervention_id', models.IntegerField(null=True)),
                ('agreement_id', models.IntegerField(null=True)),
                ('country_programme_id', models.IntegerField(null=True)),
                ('unicef_signatory_id', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pmpindicators',
            name='country_name',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
