# Generated by Django 2.1.3 on 2018-11-09 17:08

import unicef_security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_intervention_partner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HACT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=50)),
                ('schema_name', models.CharField(db_index=True, max_length=50)),
                ('year', models.IntegerField()),
                ('microassessments_total', models.IntegerField(default=0, help_text='Total number of completed Microassessments in the business area in the past year')),
                ('programmaticvisits_total', models.IntegerField(default=0, help_text='Total number of completed Programmatic visits in the business area')),
                ('followup_spotcheck', models.IntegerField(default=0, help_text='Total number of completed Programmatic visits in the business area')),
                ('completed_spotcheck', models.IntegerField(default=0, help_text='Total number of completed Programmatic visits in the business area')),
                ('completed_hact_audits', models.IntegerField(default=0, help_text='Total number of completed scheduled audits for the workspace.')),
                ('completed_special_audits', models.IntegerField(default=0, help_text='Total number of completed special audits for the workspace. ')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, unicef_security.models.TimeStampedModel),
        ),
    ]
