# Generated by Django 2.1.4 on 2018-12-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181220_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaytype',
            name='admin_level',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gatewaytype',
            unique_together={('schema_name', 'admin_level'), ('schema_name', 'name')},
        ),
    ]
