# Generated by Django 2.1.5 on 2019-02-14 16:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190214_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('alternate_id', models.IntegerField(blank=True, null=True)),
                ('alternate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('basis_for_risk_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('blocked', models.BooleanField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('core_values_assessment_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('cso_type', models.CharField(blank=True, choices=[('International', 'International'), ('National', 'National'), ('Community Based Organization', 'Community Based Organization'), ('Academic Institution', 'Academic Institution')], db_index=True, max_length=50, null=True)),
                ('deleted_flag', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(max_length=256,blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('hact_values', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(db_index=True,blank=True, null=True)),
                ('last_assessment_date', models.DateField(blank=True, null=True)),
                ('manually_blocked', models.BooleanField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255,blank=True, null=True)),
                ('net_ct_cy', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('outstanding_dct_amount_6_to_9_months_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('outstanding_dct_amount_more_than_9_months_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('partner_type', models.CharField(blank=True, choices=[('Bilateral / Multilateral', 'Bilateral / Multilateral'), ('Civil Society Organization', 'Civil Society Organization'), ('Government', 'Government'), ('UN Agency', 'UN Agency')], db_index=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=32, null=True)),
                ('rating', models.CharField(blank=True, choices=[('High', 'High'), ('Significant', 'Significant'), ('Medium', 'Medium'), ('Low', 'Low'), ('Not Required', 'Not Required')], db_index=True, max_length=50, null=True)),
                ('reported_cy', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('shared_with', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('DPKO', 'DPKO'), ('ECA', 'ECA'), ('ECLAC', 'ECLAC'), ('ESCWA', 'ESCWA'), ('FAO', 'FAO'), ('ILO', 'ILO'), ('IOM', 'IOM'), ('OHCHR', 'OHCHR'), ('UN', 'UN'), ('UN Women', 'UN Women'), ('UNAIDS', 'UNAIDS'), ('UNDP', 'UNDP'), ('UNESCO', 'UNESCO'), ('UNFPA', 'UNFPA'), ('UN - Habitat', 'UN - Habitat'), ('UNHCR', 'UNHCR'), ('UNODC', 'UNODC'), ('UNOPS', 'UNOPS'), ('UNRWA', 'UNRWA'), ('UNSC', 'UNSC'), ('UNU', 'UNU'), ('WB', 'WB'), ('WFP', 'WFP'), ('WHO', 'WHO')], max_length=20), blank=True, null=True, size=None, verbose_name='Shared Partner')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.CharField(blank=True, max_length=500, null=True)),
                ('total_ct_cp', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_ct_cy', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_ct_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('type_of_assessment', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_number', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('vision_synced', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('schema_name', 'vendor_number'), ('schema_name', 'name', 'vendor_number')},
        ),
    ]
