# Generated by Django 2.0 on 2018-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180824_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='review_date_prc',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='signed_by_partner_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='signed_by_unicef_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='submission_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='submission_date_prc',
            field=models.DateField(null=True),
        ),
    ]
