# Generated by Django 2.0 on 2018-08-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180826_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
