# Generated by Django 2.0.8 on 2018-09-10 06:16

from django.db import migrations, models


def truncate_data(*args):
    from etools_datamart.apps.data.models import PMPIndicators, Intervention
    PMPIndicators.objects.truncate()
    Intervention.objects.truncate()


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0005_auto_20180827_1445'),
    ]

    operations = [
        migrations.RunPython(
            truncate_data,
        ),
        migrations.AddField(
            model_name='intervention',
            name='schema_name',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pmpindicators',
            name='schema_name',
            field=models.CharField(db_index=True, default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intervention',
            name='country_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pmpindicators',
            name='country_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
