# Generated by Django 2.1.7 on 2019-03-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20190321_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('location_source_id', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=254, null=True)),
                ('location_pcode', models.CharField(blank=True, max_length=32, null=True)),
                ('location_level', models.IntegerField(blank=True, null=True)),
                ('location_levelname', models.CharField(blank=True, max_length=32, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date_of_completion', models.DateTimeField(blank=True, null=True)),
                ('intervention_source_id', models.IntegerField(blank=True, null=True)),
                ('intervention_number', models.CharField(max_length=64, null=True)),
                ('office', models.CharField(max_length=64, null=True)),
                ('partner_source_id', models.IntegerField()),
                ('partner_name', models.CharField(max_length=64, null=True)),
                ('engagement_source_id', models.IntegerField()),
                ('engagement_type', models.CharField(max_length=64, null=True)),
                ('section_source_id', models.IntegerField()),
                ('section_type', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
