# Generated by Django 2.1.7 on 2019-03-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_actionpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='category_module',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='category_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='high_priority',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='travel_activity_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='travel_activity_travel_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='engagement_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='engagement_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='office',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='partner_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='partner_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='section_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='section_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
