# Generated by Django 2.1.7 on 2019-03-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20190329_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpoint',
            name='partner_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
