# Generated by Django 2.2 on 2019-04-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20190411_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmvisit',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='unicef_focal_points',
            field=models.TextField(blank=True, null=True),
        ),
    ]
