# Generated by Django 2.2 on 2019-04-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20190411_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='attachments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
