# Generated by Django 2.2 on 2019-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_travel_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtoolsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(blank=True, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_staff_member', models.IntegerField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('org_unit_code', models.CharField(blank=True, max_length=32, null=True)),
                ('org_unit_name', models.CharField(blank=True, max_length=64, null=True)),
                ('post_number', models.CharField(blank=True, max_length=32, null=True)),
                ('post_title', models.CharField(blank=True, max_length=64, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=32, null=True)),
                ('vendor_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('groups', models.TextField(blank=True, null=True)),
                ('countries_available', models.TextField(blank=True, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_override', models.CharField(blank=True, max_length=100, null=True)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('oic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
