# Generated by Django 2.2 on 2019-04-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_interventionbudget'),
    ]

    operations = [
    ]
