# Generated by Django 2.2 on 2019-04-23 11:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_interventionbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='hact_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
