# Generated by Django 2.2 on 2019-04-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20190426_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelactivity',
            name='result_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='travelactivity',
            name='result_name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='travelactivity',
            name='result_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
