# Generated by Django 2.2 on 2019-05-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20190508_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionpoint',
            name='assigned_by_username',
        ),
        migrations.RemoveField(
            model_name='actionpoint',
            name='assigned_to_username',
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='action_point_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='actions_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='assigned_by_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='assigned_by_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='assigned_to_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='category_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='cp_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='cp_output_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='intervention_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='module_reference_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='module_task_activity_reference_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='reference_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='related_module',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='related_module_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='tpm_activity_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='author_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='intervention_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
