# Generated by Django 2.2 on 2019-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20190521_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionpoint',
            name='related_module',
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='engagement_subclass',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='engagement_type',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='high_priority',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('completed', 'Completed')], db_index=True, max_length=10, null=True),
        ),
    ]
