# Generated by Django 2.2 on 2019-05-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20190524_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='related_module_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
