# Generated by Django 2.2 on 2019-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20190522_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='related_module_class',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
