# Generated by Django 2.2 on 2019-05-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20190527_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('agreement_type', models.CharField(blank=True, choices=[('PCA', 'Programme Cooperation Agreement'), ('SSFA', 'Small Scale Funding Agreement'), ('MOU', 'Memorandum of Understanding')], db_index=True, max_length=10, null=True)),
                ('agreement_number', models.CharField(blank=True, max_length=45, null=True)),
                ('attached_agreement', models.CharField(blank=True, max_length=1024, null=True)),
                ('signed_by_unicef_date', models.DateField(blank=True, null=True)),
                ('signed_by_partner_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('signed', 'Signed'), ('ended', 'Ended'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], db_index=True, max_length=32, null=True)),
                ('reference_number_year', models.IntegerField(blank=True, null=True)),
                ('special_conditions_pca', models.BooleanField(blank=True, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=300, null=True)),
                ('country_programme', models.CharField(blank=True, max_length=200, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_number', models.CharField(blank=True, max_length=100, null=True)),
                ('signed_by_partner', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_authorized_officers', models.TextField(blank=True, null=True)),
                ('agreement_amendments', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('schema_name', 'agreement_number')},
            },
        ),
    ]
