# Generated by Django 2.2.2 on 2019-06-20 10:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_intervention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='cp_output',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='cp_output_id',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='intervention',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='intervention_number',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='intervention_source_id',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='intervention_title',
        ),
        migrations.RemoveField(
            model_name='interventionbylocation',
            name='cp_output',
        ),
        migrations.RemoveField(
            model_name='interventionbylocation',
            name='cp_output_id',
        ),
        migrations.AddField(
            model_name='intervention',
            name='cp_outputs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='cp_outputs_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='reference_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='agreement_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='agreement_reference_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='amendment_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='attachment_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='budget_cso_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='budget_currency',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='budget_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='budget_unicef_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='budget_unicef_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='clusters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='contingency_pd',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='country_programme',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='country_programme_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='cp_outputs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='cp_outputs_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='cso_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='days_from_prc_review_to_signature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='days_from_submission_to_signature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='document_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='fr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='intervention_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='last_amendment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='locations_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='number_of_amendments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='number_of_attachments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='offices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='offices_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_authorized_officer_signatory_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_focal_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_focal_points_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_signatory_email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_signatory_first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_signatory_last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_signatory_phone',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_signatory_title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_vendor_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='planned_programmatic_visits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='population_focus',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='prc_review_document',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='reference_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='review_date_prc',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='sections',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='signed_by_partner_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='signed_by_unicef_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='signed_pd_document',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='status',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='submission_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='submission_date_prc',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='title',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='unicef_focal_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='unicef_focal_points_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='unicef_signatory_email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='unicef_signatory_first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='unicef_signatory_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='unicef_signatory_last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='cp_outputs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='cp_outputs_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='reference_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
