# Generated by Django 2.2.2 on 2019-06-24 08:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_InterventionBudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='sections_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='sections_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='sections_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='sections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='sections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='sections',
            field=models.TextField(blank=True, null=True),
        ),
    ]
