# Generated by Django 2.2.2 on 2019-06-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_InterventionBudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='partner_signatory_email',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='partner_signatory_first_name',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='partner_signatory_last_name',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='partner_signatory_email',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='partner_signatory_first_name',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='partner_signatory_last_name',
        ),
        migrations.RemoveField(
            model_name='interventionbylocation',
            name='partner_signatory_email',
        ),
        migrations.RemoveField(
            model_name='interventionbylocation',
            name='partner_signatory_first_name',
        ),
        migrations.RemoveField(
            model_name='interventionbylocation',
            name='partner_signatory_last_name',
        ),
        migrations.AddField(
            model_name='intervention',
            name='partner_signatory_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_signatory_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='partner_signatory_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
