# Generated by Django 2.2.2 on 2019-06-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_intervention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='unicef_signatory_email',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='unicef_signatory_first_name',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='unicef_signatory_id',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='unicef_signatory_last_name',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='unicef_signatory_email',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='unicef_signatory_first_name',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='unicef_signatory_id',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='unicef_signatory_last_name',
        ),
        migrations.RemoveField(
            model_name='interventionbylocation',
            name='unicef_signatory_email',
        ),
        migrations.RemoveField(
            model_name='interventionbylocation',
            name='unicef_signatory_first_name',
        ),
        migrations.RemoveField(
            model_name='interventionbylocation',
            name='unicef_signatory_id',
        ),
        migrations.RemoveField(
            model_name='interventionbylocation',
            name='unicef_signatory_last_name',
        ),
        migrations.AddField(
            model_name='intervention',
            name='unicef_signatory_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='unicef_signatory_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='unicef_signatory_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
