# Generated by Django 2.2.2 on 2019-06-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_intervention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventionbudget',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='interventionbudget',
            name='locations_data',
        ),
        migrations.RemoveField(
            model_name='interventionbylocation',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='interventionbylocation',
            name='locations_data',
        ),
    ]
