# Generated by Django 2.2.2 on 2019-06-25 10:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionbudget',
            name='locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='locations_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
