# Generated by Django 2.2.2 on 2019-07-08 15:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_intervention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmactivity',
            name='intervention_number',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='location_source_id',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='result_name',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='section_name',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='source_intervention_id',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='source_result_id',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='source_visit_id',
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='author_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='cancel_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='cp_output',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='cp_output_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='date_of_assigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='date_of_cancelled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='date_of_tpm_accepted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='date_of_tpm_rejected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='date_of_tpm_report_rejected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='date_of_tpm_reported',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='date_of_unicef_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='locations_date',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='office',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='partner_vendor_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='pd_ssfa_reference_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='pd_ssfa_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='reject_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='section',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='task_reference_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='tpm_focal_point_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='tpm_focal_point_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='tpm_focal_points',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='tpm_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='unicef_focal_point_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='unicef_focal_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='visit_end_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='visit_reference_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='visit_start_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='visit_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='additional_information',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='area_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='attachments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='country_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='is_pv',
            field=models.BooleanField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='location_level',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='location_levelname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='location_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='location_pcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='partner_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='report_attachment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='schema_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='source_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='source_partner_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='unicef_focal_point_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='visit_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='visit_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
