# Generated by Django 2.2.2 on 2019-07-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_tpm_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tpmvisit',
            old_name='partner_vendor_number',
            new_name='vendor_number',
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='additional_information',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='cp_output',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='cp_output_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='is_pv',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='location_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='location_levelname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='location_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='location_pcode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='location_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='office',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='pd_ssfa_reference_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='pd_ssfa_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='section',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='task_reference_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='tpm_focal_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='tpm_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='visit_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='visit_reference_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='visit_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='visit_status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='visit_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='area_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='cancel_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='country_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='schema_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
