# Generated by Django 2.2.3 on 2019-07-11 12:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_t2f_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('active_pd', models.TextField(blank=True, null=True)),
                ('additional_supporting_documentation_provided', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('agreement', models.CharField(blank=True, max_length=300, null=True)),
                ('amount_refunded', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('authorized_officers', models.TextField(blank=True, null=True)),
                ('authorized_officers_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('cancel_comment', models.TextField(blank=True, null=True)),
                ('date_of_cancel', models.DateField(blank=True, null=True)),
                ('date_of_comments_by_ip', models.DateField(blank=True, null=True)),
                ('date_of_comments_by_unicef', models.DateField(blank=True, null=True)),
                ('date_of_draft_report_to_ip', models.DateField(blank=True, null=True)),
                ('date_of_draft_report_to_unicef', models.DateField(blank=True, null=True)),
                ('date_of_field_visit', models.DateField(blank=True, null=True)),
                ('date_of_final_report', models.DateField(blank=True, null=True)),
                ('date_of_report_submit', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('engagement_attachments', models.TextField(blank=True, null=True)),
                ('engagement_type', models.CharField(blank=True, choices=[('audit', 'Audit'), ('ma', 'Micro Assessment'), ('sc', 'Spot Check'), ('sa', 'Special Audit')], db_index=True, max_length=300, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('explanation_for_additional_information', models.TextField(blank=True, null=True)),
                ('joint_audit', models.BooleanField(blank=True, default=False, null=True)),
                ('justification_provided_and_accepted', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('partner_contacted_at', models.DateField(blank=True, db_index=True, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=300, null=True)),
                ('po_item', models.IntegerField(blank=True, null=True)),
                ('report_attachments', models.TextField(blank=True, null=True)),
                ('staff_members', models.TextField(blank=True, null=True)),
                ('staff_members_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('write_off_required', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('final_report', models.CharField(blank=True, max_length=300, null=True)),
                ('spotcheck_total_amount_tested', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('spotcheck_total_amount_of_ineligible_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('spotcheck_internal_controls', models.TextField(blank=True, null=True)),
                ('spotcheck_final_report', models.CharField(blank=True, max_length=300, null=True)),
                ('audited_expenditure', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('financial_findings', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('audit_opinion', models.CharField(blank=True, choices=[('unqualified', 'Unqualified'), ('qualified', 'Qualified'), ('disclaimer_opinion', 'Disclaimer opinion'), ('adverse_opinion', 'Adverse opinion')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
