# Generated by Django 2.2.3 on 2019-07-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_reports_indicators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tpmvisit',
            old_name='report_attachment',
            new_name='report_attachments',
        ),
    ]
