# Generated by Django 2.2.3 on 2019-07-23 05:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_tpm_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmvisit',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='is_pv',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='office',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='section',
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='activities_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
