# Generated by Django 2.2.3 on 2019-07-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_tpm_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportindicator',
            name='pd_output_indicator_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
