# Generated by Django 2.2.3 on 2019-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_reportindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportindicator',
            name='target_denominator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='target_numerator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
