# Generated by Django 2.2.3 on 2019-07-29 14:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_reportindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='hact_min_requirements',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='min_req_programme_visits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='min_req_spot_checks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
