# Generated by Django 2.2.3 on 2019-07-30 13:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0067_Engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='active_pd_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='partner',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
