# Generated by Django 2.2.3 on 2019-07-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_Engagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='partner_id',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='partner_source_id',
        ),
    ]
