# Generated by Django 2.2.3 on 2019-08-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0070_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='level',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=254),
        ),
    ]
