# Generated by Django 2.2.3 on 2019-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0071_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
