# Generated by Django 2.2.4 on 2019-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0075_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='last_pv_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
