# Generated by Django 2.2.4 on 2019-08-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0076_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='last_pv_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
