# Generated by Django 2.2.4 on 2019-08-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0078_TPMVisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelactivity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
