# Generated by Django 2.2.4 on 2019-08-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0085_auto_20190821_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
