# Generated by Django 2.2.4 on 2019-08-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0086_attachment_attachment_source_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gatewaytype',
            unique_together={('schema_name', 'source_id')},
        ),
    ]
