# Generated by Django 2.2.4 on 2019-09-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0088_auto_20190828_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdindicator',
            name='baseline_denominator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pdindicator',
            name='baseline_numerator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
