# Generated by Django 2.2.5 on 2019-09-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0091_engagement_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
