# Generated by Django 2.2.5 on 2019-09-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0093_auto_20190917_0603'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['source_id', 'schema_name'], name='source'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['source_id', 'schema_name'], name='source'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['source_id', 'schema_name'], name='source'),
        ),
        migrations.AddIndex(
            model_name='partnerstaffmember',
            index=models.Index(fields=['source_id', 'schema_name'], name='source'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['source_id', 'schema_name'], name='source'),
        ),
        migrations.AddIndex(
            model_name='tpmactivity',
            index=models.Index(fields=['source_id', 'schema_name'], name='source'),
        ),
        migrations.AddIndex(
            model_name='tpmvisit',
            index=models.Index(fields=['source_id', 'schema_name'], name='source'),
        ),
    ]
