# Generated by Django 2.2.5 on 2019-09-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0094_RELEASE_2_1'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['source_id', 'schema_name'], name='data_attach_source__529f94_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['source_id', 'schema_name'], name='data_engage_source__85fc81_idx'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['source_id', 'schema_name'], name='data_grant_source__df511a_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerstaffmember',
            index=models.Index(fields=['source_id', 'schema_name'], name='data_partne_source__9d46b3_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['source_id', 'schema_name'], name='data_sectio_source__565f46_idx'),
        ),
        migrations.AddIndex(
            model_name='tpmactivity',
            index=models.Index(fields=['source_id', 'schema_name'], name='data_tpmact_source__2a9531_idx'),
        ),
        migrations.AddIndex(
            model_name='tpmvisit',
            index=models.Index(fields=['source_id', 'schema_name'], name='data_tpmvis_source__90b361_idx'),
        ),
    ]
