# Generated by Django 2.2.5 on 2019-09-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0096_auto_20190919_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdindicator',
            name='target_denominator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='pdindicator',
            name='target_numerator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='baseline_denominator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='baseline_numerator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True),
        ),
    ]
