exclude: '^$'
fail_fast: false
repos:
-   repo: local
    hooks:
      - id: isort
        args:
            - --check-only
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: check-manifest
        name: check-manifest
        entry: check-manifest
        language: system
        types: [python]
        files: '^$'
        always_run: true

-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: debug-statements
        exclude: manage.py
    -   id: end-of-file-fixer
    -   id: flake8
        args:
        - src/
        - tests/
        - --config=setup.cfg
    -   id: check-merge-conflict
    -   id: check-case-conflict
-   repo: git://github.com/Yelp/detect-secrets
    rev: 0.9.1
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: (tests/.*|.*/tenant.sql|Pipfile.lock)
