version: '2'
services:
#  proxy:
#    build: ./proxy
#    ports:
#    - 8000:8000
#    depends_on:
#    - datamart
#    - flower

#  base:
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile.alpine.base
#      args:
#        VERSION: "x.x"

#  datamart:
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile.alpine
#      args:
#        BASE_IMAGE: "2.11-base"
#    environment: &environment
#      AUTOCREATE_USERS: "admin,123"
#      BASE_IMAGE: "compose"
#      CACHE_URL: "redis://redis:6379/1"
#      CACHE_URL_LOCK: "redis://redis:6379/1"
#      CACHE_URL_API: "redis://redis:6379/1"
#      CACHE_URL_TEMPLATE: "redis://redis:6379/1"
#      CELERY_BROKER_URL: "redis://redis:6379/1"
#      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
##      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq/datamart"
##      CELERY_RESULT_BACKEND: "amqp://guest:guest@rabbitmq/datamart"
#      CSRF_COOKIE_SECURE: 0
#      DATABASE_URL: postgis://postgres:@db:5432/etools_datamart
#      DATABASE_URL_ETOOLS: postgis://postgres:@etools:5432/etools
#      DEBUG: 0
#      SECRET_KEY: kuhfjhgfuytfuytfuygfuytdfuydfuygdfuygdfuytf
#      SECURE_BROWSER_XSS_FILTER: 0
#      SECURE_CONTENT_TYPE_NOSNIFF: 0
#      SECURE_FRAME_DENY: 0
#      SECURE_HSTS_PRELOAD: 0
#      SECURE_HSTS_SECONDS: 0
#      SECURE_SSL_REDIRECT: 0
#      SESSION_COOKIE_HTTPONLY: 0
#      SESSION_COOKIE_SECURE: 0
#      STATIC_ROOT: /var/datamart/static/
#      STATIC_URL: /dm-static/
#    command: datamart
#    ports:
#      - 9999:8000
#    depends_on:
#      - db
#      - etools
#      - redis

  db:
    image: mdillon/postgis:9.6
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
      POSTGRES_DB: etools_datamart
    volumes:
      - "$PWD/~build/db:/var/lib/postgresql/data"
    ports:
      - 25432:5432

  etools:
    image: mdillon/postgis:9.6
    ports:
      - "15432:5432"
    shm_size: '1gb'
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
    volumes:
      - ${VOLUME_ETOOLS_DATA}:/var/lib/postgresql/data


  redis:
    image: redis:alpine

