# TODO change this to etools-base, if etools Dockerfile-base changes accepted
# See https://github.com/unicef/etools/pull/2716
FROM unicef/etools-prp-base:latest

WORKDIR /code/
ADD Pipfile .
ADD Pipfile.lock .
RUN pipenv install --system --ignore-pipfile --deploy
