version: '2'

services:
  datamart:
  # to use this docker file with local code, set env var TAG=dev and uncomment
  # build section
    build:
      context: .
      dockerfile: ./docker/$DOCKERFILE
    image: unicef/datamart:$TAG
    environment:
      CACHE_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/2
      CELERY_RESULT_BACKEND: redis://redis:6379/3
      DATABASE_URL: postgres://postgres:@db:5432/etools_datamart
      DATABASE_URL_ETOOLS: postgis://postgres:@etools:5432/etools
      SUPERVISOR_USER: admin
      SUPERVISOR_PWD: ""
      DEBUG: "true"
      STATIC_ROOT: /tmp/static
      SECURE_SSL_REDIRECT: "false"
      SESSION_COOKIE_SECURE: "false"
      CSRF_COOKIE_SECURE: "false"
      DEVELOPMENT_MODE: "false"
      STACK: "0"
    command: datamart
    restart: "no"
    ports:
      - "8000:8000"
      - "15000:15000"
    depends_on:
      - etools
      - db
      - redis

  db:
    image: mdillon/postgis:9.5
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB: etools_datamart

  etools:
#   this image should be created running `make build` into `./db` directory
    image: unicef/etools-db:dev
    volumes:
      - /data/storage/etools-db/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

#  superset:
#    image: amancevice/superset
#    volumes:
#      - $PWD/docker:/etc/superset/

  celery:
    image: unicef/datamart:$TAG
    ports:
      - 5555:5555
      - 25000:15000
    environment:
      CACHE_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/2
      CELERY_RESULT_BACKEND: redis://redis:6379/3
      DATABASE_URL: postgres://postgres:@db:5432/etools_datamart
      DATABASE_URL_ETOOLS: postgis://postgres:@etools:5432/etools
      SUPERVISOR_USER: $SUPERVISOR_USER
      SUPERVISOR_PWD: $SUPERVISOR_PWD
      FLOWER_USER: $FLOWER_USER
      FLOWER_PWD: $FLOWER_PWD
      DEBUG: "true"
      SECURE_SSL_REDIRECT: "false"
      SESSION_COOKIE_SECURE: "false"
      CSRF_COOKIE_SECURE: "false"
      DEVELOPMENT_MODE: "false"
      STACK: "0"
    command: celery
    depends_on:
      - redis
      - db
      - etools
