version: '2'
services:
  proxy:
    image: traefik:v2.1
    command: --api.insecure=True --providers.docker
    ports:
      - "8083:80"
      - "8080:8080"
    container_name: datamart_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  datamart:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        BASE_IMAGE: "2.14-base"
    container_name: datamart
    environment:
      DEBUG: 1
      DATABASE_URL: postgis://postgres:@db:5432/etools_datamart
      DATABASE_URL_ETOOLS: postgis://postgres:@db-etools:5432/etools
      DATABASE_URL_PRP: postgis://postgres:@db-prp:5432/prp
      DATABASE_URL_UNPP: postgis://postgres:@db-unpp:5432/unpp
      AUTOCREATE_USERS: "admin,123"
      BASE_IMAGE: "compose"
      CACHE_URL: "redis://redis:6379/1"
      CACHE_URL_LOCK: "redis://redis:6379/1"
      CACHE_URL_API: "redis://redis:6379/1"
      CACHE_URL_TEMPLATE: "redis://redis:6379/1"
      CELERY_BROKER_URL: "redis://redis:6379/1"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      CSRF_COOKIE_SECURE: 0
      SECURE_BROWSER_XSS_FILTER: 0
      SECURE_CONTENT_TYPE_NOSNIFF: 0
      SECURE_FRAME_DENY: 0
      SECURE_HSTS_PRELOAD: 0
      SECURE_SSL_REDIRECT: 0
      SESSION_COOKIE_HTTPONLY: 0
      SESSION_COOKIE_SECURE: 0
      STATIC_ROOT: /code/src/etools_datamart/apps/web/static/
      GEOS_LIBRARY_PATH: "/usr/lib/libgeos_c.so.1"
      GDAL_LIBRARY_PATH: "/usr/lib/libgdal.so.26"
    command: bash -c "python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8080"
    volumes:
      - "$PWD:/code"
    labels:
      - "traefik.http.routers.datamart.rule=PathPrefix(`/`)"
      - traefik.http.routers.datamart.service=datamart
      - traefik.http.services.datamart.loadBalancer.server.port=8080
      - traefik.enable=true
    depends_on:
      - db
      - redis

  db:
    image: mdillon/postgis:9.6
    container_name: datamart_db
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
      POSTGRES_DB: etools_datamart
    volumes:
      - "$PWD/build/db:/var/lib/postgresql/data"

  # Rely on etools, prp, and unpp database instances running locally
  db-etools:
    image: mdillon/postgis:9.6
    container_name: datamart_etools
    shm_size: '1gb'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: etools
    volumes:
      - "$PWD/build/etools:/var/lib/postgresql/data"

  db-prp:
    image: mdillon/postgis:9.6
    shm_size: '1gb'
    container_name: datamart_prp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: prp
    volumes:
      - "$PWD/build/prp:/var/lib/postgresql/data"

  db-unpp:
    image: mdillon/postgis:9.6
    shm_size: '1gb'
    container_name: datamart_unpp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: unpp
    volumes:
      - "$PWD/build/unpp:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    container_name: datamart_redis
