# Generated by Django 3.2.12 on 2022-03-12 17:14

import django.db.models.deletion
from django.db import migrations, models

import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, null=True, unique=True)),
                ('value', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='EtlTaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('task', models.CharField(db_index=True, max_length=200)),
                ('elapsed', models.IntegerField(blank=True, null=True)),
                ('delta', models.IntegerField(blank=True, default=None, null=True)),
                ('delta_percentage', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('-timestamp', 'task'),
                'get_latest_by': 'last_run',
            },
        ),
        migrations.CreateModel(
            name='EtlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, unique=True)),
                ('task_id', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='UUID')),
                ('last_run', models.DateTimeField(blank=True, help_text='last execution time', null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('elapsed', models.IntegerField(blank=True, null=True)),
                ('run_type', models.IntegerField(blank=True, choices=[(0, ''), (1, 'Manual'), (2, 'cli'), (3, 'Celery'), (4, 'Forced queue'), (5, 'Required by task')], default=0)),
                ('last_success', models.DateTimeField(blank=True, help_text='last successully execution time', null=True)),
                ('last_failure', models.DateTimeField(blank=True, help_text='last failure execution time', null=True)),
                ('last_changes', models.DateTimeField(blank=True, help_text='last time data have been changed', null=True)),
                ('table_name', models.CharField(max_length=200, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('content_type', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('task',),
                'get_latest_by': 'last_run',
            },
        ),
    ]
