# Generated by Django 2.1.4 on 2018-12-12 21:19

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, unique=True)),
                ('last_run', models.DateTimeField(help_text='last execution time', null=True)),
                ('status', models.CharField(max_length=200)),
                ('elapsed', models.IntegerField(null=True)),
                ('last_success', models.DateTimeField(help_text='last successully execution time', null=True)),
                ('last_failure', models.DateTimeField(help_text='last failure execution time', null=True)),
                ('last_changes', models.DateTimeField(help_text='last time data have been changed', null=True)),
                ('table_name', models.CharField(max_length=200, null=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'get_latest_by': 'last_run',
            },
        ),
    ]
