# Generated by Django 2.1.2 on 2018-10-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('result', models.CharField(max_length=200)),
                ('elapsed', models.IntegerField(null=True)),
                ('last_success', models.DateTimeField(null=True)),
                ('last_failure', models.DateTimeField(null=True)),
                ('table_name', models.CharField(max_length=200, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
