# Generated by Django 2.1.7 on 2019-03-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etltask',
            name='elapsed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etltask',
            name='last_changes',
            field=models.DateTimeField(blank=True, help_text='last time data have been changed', null=True),
        ),
        migrations.AlterField(
            model_name='etltask',
            name='last_failure',
            field=models.DateTimeField(blank=True, help_text='last failure execution time', null=True),
        ),
        migrations.AlterField(
            model_name='etltask',
            name='last_success',
            field=models.DateTimeField(blank=True, help_text='last successully execution time', null=True),
        ),
        migrations.AlterField(
            model_name='etltask',
            name='run_type',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'Manual'), (2, 'cli'), (3, 'Celery'), (4, 'Forced queue'), (5, 'Required by task')], default=0),
        ),
    ]
