# Generated by Django 2.1.3 on 2018-11-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskLog',
            new_name='EtlTask',
        ),
    ]
