# Generated by Django 2.0 on 2018-08-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='last_failure',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='last_success',
            field=models.DateTimeField(null=True),
        ),
    ]
