# Generated by Django 2.0 on 2018-08-29 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('etl', '0002_auto_20180828_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='execution',
            name='table_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
