# Generated by Django 2.2 on 2019-05-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_auto_20190303_0335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etltask',
            options={'get_latest_by': 'last_run', 'ordering': ('task',)},
        ),
    ]
