# Generated by Django 2.0 on 2018-08-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('etl', '0003_auto_20180829_1156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Execution',
            new_name='TaskLog',
        ),
    ]
