# Generated by Django 2.2.4 on 2019-08-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_auto_20190501_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='etltask',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='etltask',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etltask',
            name='last_run',
            field=models.DateTimeField(blank=True, help_text='last execution time', null=True),
        ),
        migrations.AlterField(
            model_name='etltask',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
