# Generated by Django 2.1.3 on 2018-11-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_auto_20181123_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etltask',
            old_name='timestamp',
            new_name='last_run',
        ),
    ]
