# Generated by Django 2.0 on 2018-09-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_auto_20180829_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='elapsed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
