# Generated by Django 2.1.3 on 2018-11-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_auto_20181126_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='etltask',
            name='last_changes',
            field=models.DateTimeField(null=True),
        ),
    ]
