# Generated by Django 2.2.4 on 2019-08-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_auto_20190830_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlTaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('task', models.CharField(db_index=True, max_length=200)),
                ('elapsed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('task',),
                'get_latest_by': 'last_run',
            },
        ),
    ]
