# Generated by Django 2.0.8 on 2018-09-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_auto_20180903_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='task',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
