# Generated by Django 2.2.4 on 2019-09-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_etltaskhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etltaskhistory',
            options={'get_latest_by': 'last_run', 'ordering': ('task', '-timestamp')},
        ),
        migrations.AddField(
            model_name='etltaskhistory',
            name='delta',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
