# Generated by Django 2.2.4 on 2019-09-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_auto_20190905_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='etltaskhistory',
            name='delta_percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
