# Generated by Django 2.2.5 on 2019-09-06 11:17

from django.db import migrations, models

import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_etltaskhistory_delta_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, null=True, unique=True)),
                ('value', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
