# Generated by Django 2.2.5 on 2019-09-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etltaskhistory',
            options={'get_latest_by': 'last_run', 'ordering': ('-timestamp', 'task')},
        ),
    ]
