# Generated by Django 3.1.6 on 2021-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0009_auto_20190907_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etltask',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
