ARG BASE_IMAGE
FROM unicef/datamart:${BASE_IMAGE}

ADD Pipfile .
Add Pipfile.lock .

RUN apk add bash
RUN mkdir /tmp/static

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /code
ENV DJANGO_SETTINGS_MODULE etools_datamart.config.settings

VOLUME "./:/code/"
WORKDIR /code/
