# Generated by Django 3.2.12 on 2022-03-12 17:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='auth.group')),
            ],
            options={
                'verbose_name': 'Schemas ACL',
                'verbose_name_plural': 'Schemas ACLs',
                'ordering': ('group',),
            },
        ),
    ]
