# Generated by Django 2.1.2 on 2018-10-25 12:44

import django_countries.fields
import unicef_security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatamartBusinessArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('long_name', models.CharField(max_length=150, verbose_name='long name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            bases=(models.Model, unicef_security.models.TimeStampedModel),
        ),
    ]
