# Generated by Django 4.2.11 on 2024-04-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0002_queryfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="querylog",
            name="success",
            field=models.BooleanField(default=True),
        ),
    ]
