# Generated by Django 4.2.13 on 2024-07-24 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("explorer", "0003_querylog_error_querylog_success"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExplorerValue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("UUID", "Install Unique ID"),
                            ("SMLS", "Startup metric last send"),
                            ("ASP", "System prompt for SQL Assistant"),
                        ],
                        max_length=5,
                        unique=True,
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromptLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prompt", models.TextField(blank=True)),
                ("response", models.TextField(blank=True)),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "run_by_user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
