# Generated by Django 4.2.11 on 2024-09-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0004_explorervalue_promptlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExplorerValue",
        ),
        migrations.DeleteModel(
            name="PromptLog",
        ),
    ]
