# Generated by Django 2.2.17 on 2021-01-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0008_auto_20190710_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['title'], 'verbose_name': 'Query', 'verbose_name_plural': 'Queries'},
        ),
        migrations.AlterField(
            model_name='query',
            name='connection',
            field=models.CharField(blank=True, default='', help_text='Name of DB connection (as specified in settings) to use for this query.Will use EXPLORER_DEFAULT_CONNECTION if left blank', max_length=128),
        ),
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='connection',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='sql',
            field=models.TextField(blank=True),
        ),
    ]
