# Generated by Django 3.1.6 on 2021-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidpro', '0003_remove_flow_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='groups',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='flowstart',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='flowstart',
            name='restart_participants',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='credits',
            field=models.JSONField(default=dict),
        ),
    ]
