# Generated by Django 2.1 on 2018-08-10 10:39

import uuid

import concurrency.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import strategy_field.fields
import unicef_rest_framework.models.acl
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier', unique=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField()),
                ('allowed_ip', models.CharField(default='.*', help_text='Regex to validate remote IP', max_length=255)),
                ('all_services', models.BooleanField(default=False, help_text='allow any service, even future created')),
                ('last_modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier', unique=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('last_modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier', unique=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='unique service name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('viewset', strategy_field.fields.StrategyClassField(db_index=True, help_text='class FQN', unique=True)),
                ('access', models.IntegerField(choices=[(0, 'Open'), (2, 'Login required'), (4, 'Access Restricted'), (8, 'Business authorization needed')], default=2, help_text='Required privileges')),
                ('confidentiality', models.IntegerField(choices=[(1, 'Strictly Confidential'), (2, 'Confidential'), (3, 'Internal'), (4, 'Internal UN'), (5, 'Public')], default=3)),
                ('hidden', models.BooleanField(default=False)),
                ('cache_version', models.IntegerField(default=1)),
                ('cache_ttl', models.CharField(default='1d', max_length=5)),
                ('cache_key', models.CharField(blank=True, help_text='Key used to invalidate service cache', max_length=1000, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unicef_rest_framework.Category')),
                ('last_modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_models', models.ManyToManyField(blank=True, help_text='models that the service depends on', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('name',),
                'permissions': (('do_not_scramble', 'Can read any service unscrambled'),),
            },
        ),
        migrations.CreateModel(
            name='SystemFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('handler', models.CharField(default='unicef_rest_framework.models.filter.SystemFilterHandler', max_length=500)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unicef_rest_framework.Application')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicef_rest_framework.Service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemFilterFieldRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=500)),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
                ('override_field', models.BooleanField(default=False)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='unicef_rest_framework.SystemFilter')),
            ],
        ),
        migrations.CreateModel(
            name='SystemFilterParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=300)),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicef_rest_framework.SystemFilter')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier', unique=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('rate', models.CharField(max_length=50)),
                ('serializers', django.contrib.postgres.fields.ArrayField(base_field=unicef_rest_framework.models.acl.SerializerField(max_length=200), blank=True, default=unicef_rest_framework.models.acl.default_serializer, size=None)),
                ('last_modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicef_rest_framework.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User ACL',
                'verbose_name_plural': 'User ACLs',
                'ordering': ('user',),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='allowed services', to='unicef_rest_framework.Service'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CacheVersion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('unicef_rest_framework.service',),
        ),
        migrations.AlterUniqueTogether(
            name='systemfilterparam',
            unique_together={('filter', 'param')},
        ),
        migrations.AlterUniqueTogether(
            name='systemfilterfieldrule',
            unique_together={('filter', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='systemfilter',
            unique_together={('service', 'application'), ('service', 'user'), ('service', 'group')},
        ),
    ]
