# Generated by Django 2.1.4 on 2018-12-23 09:05

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import concurrency.fields
import strategy_field.fields

import unicef_rest_framework.models.acl


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', unique=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField()),
                ('allowed_ip', models.CharField(default='.*', help_text='Regex to validate remote IP', max_length=255)),
                ('all_services', models.BooleanField(default=False, help_text='allow any service, even future created')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GroupAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', unique=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('rate', models.CharField(default='*', max_length=50)),
                ('serializers', django.contrib.postgres.fields.ArrayField(base_field=unicef_rest_framework.models.acl.SerializerField(max_length=200), blank=True, default=unicef_rest_framework.models.acl.default_serializer, size=None)),
                ('policy', models.IntegerField(choices=[(0, 'Forbid'), (1, 'Grant'), (2, 'Default')])),
            ],
            options={
                'verbose_name': 'Group ACL',
                'verbose_name_plural': 'Group ACLs',
                'ordering': ('group', 'service'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', unique=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='unique service name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('viewset', strategy_field.fields.StrategyClassField(db_index=True, help_text='class FQN', unique=True)),
                ('basename', models.CharField(help_text='viewset basename', max_length=200)),
                ('suffix', models.CharField(help_text='url suffix', max_length=200)),
                ('url_name', models.CharField(help_text='url name as per drf reverse', max_length=300)),
                ('access', models.IntegerField(choices=[(0, 'Open'), (2, 'Login required'), (4, 'Access Restricted'), (8, 'Business authorization needed')], default=2, help_text='Required privileges')),
                ('confidentiality', models.IntegerField(choices=[(1, 'Strictly Confidential'), (2, 'Confidential'), (3, 'Internal'), (4, 'Internal UN'), (5, 'Public')], default=3)),
                ('hidden', models.BooleanField(default=False)),
                ('cache_version', models.IntegerField(default=1)),
                ('cache_ttl', models.CharField(default='1d', max_length=5)),
                ('cache_key', models.CharField(blank=True, help_text='Key used to invalidate service cache', max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SystemFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('handler', models.CharField(default='unicef_rest_framework.models.filter.SystemFilterHandler', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SystemFilterFieldRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=500)),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
                ('override_field', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemFilterParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=300)),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', unique=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('rate', models.CharField(default='*', max_length=50)),
                ('serializers', django.contrib.postgres.fields.ArrayField(base_field=unicef_rest_framework.models.acl.SerializerField(max_length=200), blank=True, default=unicef_rest_framework.models.acl.default_serializer, size=None)),
                ('policy', models.IntegerField(choices=[(0, 'Forbid'), (1, 'Grant'), (2, 'Default')])),
            ],
            options={
                'verbose_name': 'User ACL',
                'verbose_name_plural': 'User ACLs',
                'ordering': ('user', 'service'),
            },
        ),
        migrations.CreateModel(
            name='UserServiceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000)),
                ('expires', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicef_rest_framework.Service')),
            ],
        ),
    ]
