# Generated by Django 2.0 on 2018-08-25 19:21

from django.conf import settings
from django.db import migrations


def forwards_func(apps, schema_editor):
    from unicef_rest_framework.models import Service
    Service.objects.load_services()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unicef_rest_framework', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
