# Generated by Django 4.0.5 on 2022-06-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('unicef_rest_framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='linked_models',
            field=models.ManyToManyField(blank=True, help_text='models that the service depends on', related_name='+', to='contenttypes.contenttype'),
        ),
    ]
