# Generated by Django 2.1.4 on 2018-12-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_rest_framework', '0002_auto_20181207_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='basename',
            field=models.CharField(default='', help_text='viewset basename', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='url_name',
            field=models.CharField(default='', help_text='url name as per drf reverse', max_length=300),
            preserve_default=False,
        ),
    ]
