# Generated by Django 3.2.16 on 2022-11-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_rest_framework', '0002_alter_service_linked_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='format',
            field=models.CharField(choices=[('text/plain', 'txt'), ('text/csv', 'csv'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'xlsx'), ('application/json', 'json')], max_length=100),
        ),
    ]
