# Generated by Django 2.0 on 2018-08-26 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('unicef_rest_framework', '0002_refresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.IntegerField(choices=[(0, 'Forbid'), (1, 'Grant'), (2, 'Default')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='last_modify_user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='systemfilter',
            unique_together={('service', 'user'), ('service', 'group')},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='authorization',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicef_rest_framework.Service'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
