# Generated by Django 3.2.16 on 2023-01-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_rest_framework', '0003_alter_export_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, help_text='unique service name', max_length=200, unique=True),
        ),
    ]
