# Generated by Django 2.2.5 on 2019-09-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_rest_framework', '0003_preload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preload',
            old_name='last_status_code',
            new_name='status_code',
        ),
        migrations.AddField(
            model_name='preload',
            name='response_ms',
            field=models.PositiveIntegerField(default=0, verbose_name='ms', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preload',
            name='response_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
