# Generated by Django 2.0 on 2018-08-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_rest_framework', '0003_auto_20180826_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='group',
        ),
        migrations.RemoveField(
            model_name='authorization',
            name='service',
        ),
        migrations.RemoveField(
            model_name='authorization',
            name='user',
        ),
        migrations.AddField(
            model_name='useraccesscontrol',
            name='policy',
            field=models.IntegerField(choices=[(0, 'Forbid'), (1, 'Grant'), (2, 'Default')], default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Authorization',
        ),
    ]
