# Generated by Django 2.2.7 on 2019-11-28 22:48

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unicef_rest_framework', '0004_auto_20190908_0646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preload',
            options={},
        ),
        migrations.AddField(
            model_name='preload',
            name='etag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='preload',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('enabled', models.BooleanField(blank=True, default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_length', models.IntegerField(blank=True, null=True)),
                ('response_ms', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ms')),
                ('etag', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('text/plain', 'txt'), ('text/csv', 'csv'), ('application/xlsx', 'xlsx'), ('application/json', 'json')], max_length=30)),
                ('refresh', models.BooleanField(default=False, help_text='If true data are refreshed every day')),
                ('filename', models.CharField(help_text='Optional file name', max_length=100)),
                ('save_as', models.BooleanField(default=False, help_text='If true, DataMart will try to force "SaveAs" popup. Note that popup will be displayed in any case if browser do not natively support requested format')),
                ('as_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('url', 'as_user', 'params', 'format')},
            },
        ),
    ]
