# Generated by Django 4.2.3 on 2023-10-13 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("unicef_rest_framework", "0004_alter_service_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="export",
            unique_together={("url", "params", "format")},
        ),
    ]
