# Generated by Django 2.2.7 on 2019-11-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_rest_framework', '0005_auto_20191128_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='notify',
            field=models.BooleanField(default=False, help_text='Send me an email when file is available'),
        ),
    ]
