# Generated by Django 2.0.8 on 2018-09-05 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unicef_rest_framework', '0005_auto_20180828_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccesscontrol',
            options={'ordering': ('user', 'service'), 'verbose_name': 'User ACL', 'verbose_name_plural': 'User ACLs'},
        ),
        migrations.AlterUniqueTogether(
            name='useraccesscontrol',
            unique_together={('user', 'service')},
        ),
    ]
