# Generated by Django 4.2.13 on 2024-07-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unicef_rest_framework", "0005_alter_export_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportAccessLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("access_history", models.JSONField(blank=True, default=list, null=True)),
                (
                    "export",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unicef_rest_framework.export",
                    ),
                ),
            ],
        ),
    ]
