# Generated by Django 4.2.11 on 2024-09-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unicef_rest_framework", "0006_exportaccesslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportaccesslog",
            name="access_history",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="exportaccesslog",
            name="export",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="unicef_rest_framework.export", unique=True
            ),
        ),
    ]
