# Generated by Django 3.0.12 on 2021-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_rest_framework', '0006_export_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
