# Generated by Django 3.1.6 on 2021-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_rest_framework', '0007_auto_20210210_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='preload',
            name='params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
