# Generated by Django 3.2.12 on 2022-03-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmontrack',
            name='field_office',
        ),
        migrations.AddField(
            model_name='fmontrack',
            name='field_offices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
