# Generated by Django 2.1.5 on 2019-02-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190213_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('additional_note', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_cost_travel_agencies', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('approved_cost_traveler', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_note', models.TextField(blank=True, null=True)),
                ('certification_note', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=5, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('estimated_travel_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('first_submission_date', models.DateTimeField(blank=True, null=True)),
                ('hidden', models.BooleanField(blank=True, null=True)),
                ('international_travel', models.NullBooleanField()),
                ('is_driver', models.BooleanField(blank=True, null=True)),
                ('misc_expenses', models.TextField(blank=True, null=True)),
                ('mode_of_travel', models.TextField(blank=True, null=True)),
                ('office_name', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('preserved_expenses_local', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('preserved_expenses_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=12, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('report_note', models.TextField(blank=True, null=True)),
                ('section_name', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('sent_for_payment', 'Sent for payment'), ('certification_submitted', 'Certification submitted'), ('certification_approved', 'Certification approved'), ('certification_rejected', 'Certification rejected'), ('certified', 'Certified'), ('completed', 'Completed')], db_index=True, max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_email', models.CharField(blank=True, max_length=200, null=True)),
                ('ta_required', models.NullBooleanField()),
                ('traveler_email', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='travel',
            unique_together={('schema_name', 'reference_number')},
        ),
    ]
