# Generated by Django 3.2.12 on 2022-04-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20220407_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etoolsuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='etoolsuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
