# Generated by Django 2.1.7 on 2019-02-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190214_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdindicator',
            name='intervention',
        ),
        migrations.AddField(
            model_name='pdindicator',
            name='location_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdindicator',
            name='location_levelname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pdindicator',
            name='location_pcode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gatewaytype',
            name='source_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
