# Generated by Django 3.2.12 on 2022-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20220420_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotcheckfindings',
            name='date_of_field_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
