# Generated by Django 2.1.7 on 2019-02-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190226_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('location_source_id', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=254, null=True)),
                ('location_pcode', models.CharField(blank=True, max_length=32, null=True)),
                ('location_level', models.IntegerField(blank=True, null=True)),
                ('location_levelname', models.CharField(blank=True, max_length=32, null=True)),
                ('travel_reference_number', models.CharField(blank=True, max_length=200, null=True)),
                ('travel_type', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('partnership_number', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_traveler', models.CharField(blank=True, max_length=200, null=True)),
                ('source_travel_id', models.IntegerField(null=True)),
                ('source_partner_id', models.IntegerField(null=True)),
                ('source_partnership_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pdindicator',
            name='location_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='travelactivity',
            unique_together={('schema_name', 'source_id', 'travel_reference_number', 'location_source_id')},
        ),
    ]
