# Generated by Django 3.2.12 on 2022-05-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_spotcheckfindings_date_of_field_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='key_internal_control_weaknesses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
