# Generated by Django 2.1.7 on 2019-03-21 10:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190302_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionByLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('location_source_id', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=254, null=True)),
                ('location_pcode', models.CharField(blank=True, max_length=32, null=True)),
                ('location_level', models.IntegerField(blank=True, null=True)),
                ('location_levelname', models.CharField(blank=True, max_length=32, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(null=True)),
                ('document_type', models.CharField(max_length=255, null=True)),
                ('number', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(db_index=True, max_length=256, null=True)),
                ('status', models.CharField(max_length=32, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('submission_date', models.DateField(null=True)),
                ('submission_date_prc', models.DateField(null=True)),
                ('review_date_prc', models.DateField(null=True)),
                ('prc_review_document', models.CharField(max_length=1024, null=True)),
                ('signed_by_unicef_date', models.DateField(null=True)),
                ('signed_by_partner_date', models.DateField(null=True)),
                ('population_focus', models.CharField(max_length=130, null=True)),
                ('partner_authorized_officer_signatory_id', models.IntegerField(null=True)),
                ('signed_pd_document', models.CharField(max_length=1024, null=True)),
                ('contingency_pd', models.NullBooleanField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('unicef_signatory_first_name', models.CharField(max_length=30, null=True)),
                ('unicef_signatory_last_name', models.CharField(max_length=30, null=True)),
                ('unicef_signatory_email', models.CharField(max_length=254, null=True)),
                ('partner_name', models.CharField(max_length=200, null=True)),
                ('partner_signatory_title', models.CharField(max_length=64, null=True)),
                ('partner_signatory_first_name', models.CharField(max_length=64, null=True)),
                ('partner_signatory_last_name', models.CharField(max_length=64, null=True)),
                ('partner_signatory_email', models.CharField(max_length=128, null=True)),
                ('partner_signatory_phone', models.CharField(max_length=64, null=True)),
                ('unicef_focal_point_first_name', models.CharField(max_length=30, null=True)),
                ('unicef_focal_point_last_name', models.CharField(max_length=30, null=True)),
                ('unicef_focal_point_email', models.CharField(max_length=254, null=True)),
                ('partner_focal_point_title', models.CharField(max_length=64, null=True)),
                ('partner_focal_point_first_name', models.CharField(max_length=64, null=True)),
                ('partner_focal_point_last_name', models.CharField(max_length=64, null=True)),
                ('partner_focal_point_email', models.CharField(max_length=128, null=True)),
                ('partner_focal_point_phone', models.CharField(max_length=64, null=True)),
                ('partner_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unicef_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('in_kind_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('partner_contribution_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unicef_cash_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('in_kind_amount_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=4, null=True)),
                ('intervention_id', models.IntegerField(blank=True, null=True)),
                ('agreement_id', models.IntegerField(blank=True, null=True)),
                ('country_programme_id', models.IntegerField(blank=True, null=True)),
                ('unicef_signatory_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Intervention By Location',
                'ordering': ('country_name', 'title'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='interventionbylocation',
            unique_together={('schema_name', 'intervention_id', 'location_source_id')},
        ),
    ]
