# Generated by Django 3.1.13 on 2022-05-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_engagement_key_internal_control_weaknesses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GatewayType',
        ),
    ]
