# Generated by Django 3.2.12 on 2022-05-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_delete_gatewaytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submission', 'Submission Review'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('review', 'Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('office_name', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('section_name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('supervisor_email', models.CharField(blank=True, max_length=200, null=True)),
                ('traveler_email', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('user_info_text', models.JSONField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('not_as_planned', models.BooleanField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('schema_name', 'reference_number')},
            },
        ),
    ]
