# Generated by Django 2.2 on 2019-04-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20190405_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPMActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('location_source_id', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=254, null=True)),
                ('location_pcode', models.CharField(blank=True, max_length=32, null=True)),
                ('location_level', models.IntegerField(blank=True, null=True)),
                ('location_levelname', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('is_pv', models.BooleanField(blank=True, null=True)),
                ('intervention_number', models.CharField(blank=True, max_length=128, null=True)),
                ('result_name', models.CharField(blank=True, max_length=128, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=128, null=True)),
                ('unicef_focal_point_name', models.CharField(blank=True, max_length=128, null=True)),
                ('visit_status', models.CharField(blank=True, max_length=128, null=True)),
                ('visit_information', models.CharField(blank=True, max_length=128, null=True)),
                ('section_name', models.CharField(blank=True, max_length=128, null=True)),
                ('source_visit_id', models.IntegerField(blank=True, null=True)),
                ('source_result_id', models.IntegerField(blank=True, null=True)),
                ('source_partner_id', models.IntegerField(blank=True, null=True)),
                ('source_intervention_id', models.IntegerField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('report_attachment', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TPMVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('reject_comment', models.TextField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('visit_information', models.TextField(blank=True, null=True)),
                ('date_of_assigned', models.DateField(blank=True, null=True)),
                ('date_of_cancelled', models.DateField(blank=True, null=True)),
                ('date_of_tpm_accepted', models.DateField(blank=True, null=True)),
                ('date_of_tpm_rejected', models.DateField(blank=True, null=True)),
                ('date_of_tpm_reported', models.DateField(blank=True, null=True)),
                ('date_of_tpm_report_rejected', models.DateField(blank=True, null=True)),
                ('date_of_unicef_approved', models.DateField(blank=True, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=120, null=True)),
                ('partner_vendor_number', models.CharField(blank=True, max_length=120, null=True)),
                ('cancel_comment', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=120, null=True)),
                ('source_partner_id', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
