# Generated by Django 4.0.5 on 2022-06-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_traveltrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerstaffmember',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
