# Generated by Django 3.2.13 on 2022-06-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_traveltrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerstaffmember',
            name='partner_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
