# Generated by Django 3.2.13 on 2022-06-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_partnerstaffmember_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='final_partnership_review',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
