# Generated by Django 2.2 on 2019-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_tpmactivity_tpmvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmvisit',
            name='attachments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='report_attachment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
