# Generated by Django 3.2.13 on 2022-07-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_intervention_final_partnership_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportindicator',
            name='partner_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportindicator',
            name='partner_vendor_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
