# Generated by Django 3.2.16 on 2022-11-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20220729_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='hyperlink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
