# Generated by Django 2.2 on 2019-04-18 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_etoolsuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('partner_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unicef_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('in_kind_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('partner_contribution_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unicef_cash_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('in_kind_amount_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=4, null=True)),
                ('intervention_title', models.CharField(blank=True, max_length=256, null=True)),
                ('intervention_number', models.CharField(blank=True, max_length=64, null=True)),
                ('intervention_source_id', models.IntegerField(blank=True, null=True)),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Intervention')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
