# Generated by Django 4.1.5 on 2023-03-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_audit_end_date_audit_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='outstanding_amt_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='outstanding_amt_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='outstanding_amt_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
