# Generated by Django 4.1.5 on 2023-02-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_audit_end_date_audit_start_date'),
        ('data', '0015_interventionactivity_interventioncountryprogramme_interventionepd_interventionmanagementbudget_inter'),
    ]

    operations = [
    ]
