# Generated by Django 2.2 on 2019-04-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20190423_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelactivity',
            name='result_code',
        ),
        migrations.RemoveField(
            model_name='travelactivity',
            name='result_sector',
        ),
        migrations.RemoveField(
            model_name='travelactivity',
            name='result_type',
        ),
        migrations.RemoveField(
            model_name='travelactivity',
            name='result_vision_id',
        ),
        migrations.RemoveField(
            model_name='travelactivity',
            name='source_result_id',
        ),
    ]
