# Generated by Django 4.1.5 on 2023-03-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_merge_20230206_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionPlannedVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('partner_vendor_number', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_name', models.CharField(max_length=200, null=True)),
                ('pd_status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('active', 'Active'), ('ended', 'Ended'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], db_index=True, max_length=32, null=True)),
                ('pd_reference_number', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('programmatic_q1', models.IntegerField(default=0)),
                ('programmatic_q2', models.IntegerField(default=0)),
                ('programmatic_q3', models.IntegerField(default=0)),
                ('programmatic_q4', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Intervention Planned Visits',
                'ordering': ('-created',),
            },
        ),
    ]
