# Generated by Django 4.1.5 on 2023-04-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0019_auditfinancialfinding"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnersPlannedEngagement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                ("seen", models.DateTimeField(blank=True, null=True)),
                ("country_name", models.CharField(max_length=100)),
                ("schema_name", models.CharField(db_index=True, max_length=63)),
                ("area_code", models.CharField(db_index=True, max_length=10)),
                (
                    "partner_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "vendor_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("spot_check_planned_q1", models.IntegerField(blank=True, null=True)),
                ("spot_check_planned_q2", models.IntegerField(blank=True, null=True)),
                ("spot_check_planned_q3", models.IntegerField(blank=True, null=True)),
                ("spot_check_planned_q4", models.IntegerField(blank=True, null=True)),
                ("scheduled_audit", models.BooleanField(blank=True, null=True)),
                ("special_audit", models.BooleanField(blank=True, null=True)),
                ("spot_check_follow_up", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
