# Generated by Django 2.2 on 2019-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20190426_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='partner_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='partner_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
