# Generated by Django 4.1.8 on 2023-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0020_partnersplannedengagement"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotcheckfindings",
            name="offices",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spotcheckfindings",
            name="offices_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
