# Generated by Django 4.1.8 on 2023-05-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0021_spotcheckfindings_offices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="terms_acknowledged_by",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="engagement",
            name="year_of_audit",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="final_review_approved",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="has_activities_involving_children",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="has_data_processing_agreement",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="has_special_conditions_for_construction",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="other_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interventionbudget",
            name="final_review_approved",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interventionbudget",
            name="has_activities_involving_children",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interventionbudget",
            name="has_data_processing_agreement",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interventionbudget",
            name="has_special_conditions_for_construction",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interventionbudget",
            name="other_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interventionbylocation",
            name="final_review_approved",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interventionbylocation",
            name="has_activities_involving_children",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interventionbylocation",
            name="has_data_processing_agreement",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interventionbylocation",
            name="has_special_conditions_for_construction",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interventionbylocation",
            name="other_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="title",
            field=models.CharField(db_index=True, max_length=306, null=True),
        ),
        migrations.AlterField(
            model_name="interventionbudget",
            name="title",
            field=models.CharField(db_index=True, max_length=306, null=True),
        ),
        migrations.AlterField(
            model_name="interventionbylocation",
            name="title",
            field=models.CharField(db_index=True, max_length=306, null=True),
        ),
    ]
