# Generated by Django 4.1.8 on 2023-05-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0021_spotcheckfindings_offices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="title",
            field=models.CharField(db_index=True, max_length=306, null=True),
        ),
        migrations.AlterField(
            model_name="interventionbudget",
            name="title",
            field=models.CharField(db_index=True, max_length=306, null=True),
        ),
        migrations.AlterField(
            model_name="interventionbylocation",
            name="title",
            field=models.CharField(db_index=True, max_length=306, null=True),
        ),
    ]
