# Generated by Django 4.1.9 on 2023-05-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0021_spotcheckfindings_offices_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                ("seen", models.DateTimeField(blank=True, null=True)),
                ("country_name", models.CharField(max_length=100)),
                ("schema_name", models.CharField(db_index=True, max_length=63)),
                ("area_code", models.CharField(db_index=True, max_length=10)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("names_of_other_agencies", models.CharField(blank=True, max_length=255, null=True)),
                ("partner_name", models.CharField(blank=True, max_length=300, null=True)),
                ("vendor_number", models.CharField(blank=True, max_length=30, null=True)),
                ("expected_budget", models.IntegerField(blank=True, null=True)),
                ("requested_date", models.DateField()),
                ("planned_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("rating", models.CharField(blank=True, max_length=50, null=True)),
                ("report", models.CharField(blank=True, max_length=1024, null=True)),
                ("current", models.BooleanField(blank=True, null=True)),
                ("approving_officer", models.CharField(blank=True, max_length=200, null=True)),
                ("requesting_officer", models.CharField(blank=True, max_length=200, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
