# Generated by Django 4.1.8 on 2023-05-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0022_agreement_terms_acknowledged_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interventionactivity",
            name="pd_title",
            field=models.CharField(db_index=True, max_length=306, null=True),
        ),
        migrations.AlterField(
            model_name="interventioncountryprogramme",
            name="pd_title",
            field=models.CharField(db_index=True, max_length=306, null=True),
        ),
        migrations.AlterField(
            model_name="interventionepd",
            name="pd_title",
            field=models.CharField(db_index=True, max_length=306, null=True),
        ),
        migrations.AlterField(
            model_name="interventionmanagementbudget",
            name="pd_title",
            field=models.CharField(db_index=True, max_length=306, null=True),
        ),
        migrations.AlterField(
            model_name="interventionreview",
            name="pd_title",
            field=models.CharField(db_index=True, max_length=306, null=True),
        ),
    ]
