# Generated by Django 4.1.8 on 2023-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0023_assessment"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundsReservationItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                ("seen", models.DateTimeField(blank=True, null=True)),
                ("country_name", models.CharField(max_length=100)),
                ("schema_name", models.CharField(db_index=True, max_length=63)),
                ("area_code", models.CharField(db_index=True, max_length=10)),
                ("fund_reservation_number", models.CharField(max_length=20)),
                ("fr_ref_number", models.CharField(max_length=30)),
                ("line_item", models.SmallIntegerField()),
                ("wbs", models.CharField(max_length=30)),
                ("grant_number", models.CharField(max_length=20)),
                ("fund", models.CharField(max_length=10)),
                ("overall_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("overall_amount_dc", models.DecimalField(decimal_places=2, max_digits=20)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("line_item_text", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                ("donor", models.CharField(blank=True, max_length=256, null=True)),
                ("donor_code", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "unique_together": {("fund_reservation_number", "line_item")},
            },
        ),
        migrations.CreateModel(
            name="FundsReservationHeader",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                ("seen", models.DateTimeField(blank=True, null=True)),
                ("country_name", models.CharField(max_length=100)),
                ("schema_name", models.CharField(db_index=True, max_length=63)),
                ("area_code", models.CharField(db_index=True, max_length=10)),
                ("vendor_code", models.CharField(max_length=20)),
                ("fr_number", models.CharField(max_length=20)),
                ("document_date", models.DateField(blank=True, null=True)),
                ("fr_type", models.CharField(max_length=50)),
                ("currency", models.CharField(max_length=50)),
                ("document_text", models.CharField(max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("actual_amt", models.DecimalField(decimal_places=2, max_digits=20)),
                ("intervention_amt", models.DecimalField(decimal_places=2, max_digits=20)),
                ("outstanding_amt", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total_amt", models.DecimalField(decimal_places=2, max_digits=20)),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                ("actual_amt_local", models.DecimalField(decimal_places=2, max_digits=20)),
                ("outstanding_amt_local", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total_amt_local", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("multi_curr_flag", models.BooleanField()),
                ("completed_flag", models.BooleanField(blank=True, default=None, null=True)),
                ("delegated", models.BooleanField(blank=True, default=None, null=True)),
                ("pd_reference_number", models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                "unique_together": {("fr_number", "vendor_code")},
            },
        ),
    ]
