# Generated by Django 4.2 on 2023-06-12 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0024_assessment_fundsreservationitem_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fundsreservationheader",
            unique_together={("schema_name", "fr_number", "vendor_code")},
        ),
        migrations.AlterUniqueTogether(
            name="fundsreservationitem",
            unique_together={("schema_name", "fund_reservation_number", "line_item")},
        ),
    ]
