# Generated by Django 4.1.8 on 2023-06-15 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0025_alter_fundsreservationheader_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FundsReservationItem",
        ),
    ]
