# Generated by Django 4.1.8 on 2023-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0026_delete_fundsreservationitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("last_modify_date", models.DateTimeField(auto_now=True)),
                ("seen", models.DateTimeField(blank=True, null=True)),
                ("schema_name", models.CharField(max_length=63)),
                ("name", models.CharField(max_length=100)),
                ("business_area_code", models.CharField(max_length=10)),
                ("initial_zoom", models.IntegerField()),
                ("latitude", models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ("country_short_code", models.CharField(max_length=10)),
                ("vision_sync_enabled", models.BooleanField()),
                ("vision_last_synced", models.DateTimeField(blank=True, null=True)),
                ("currency_code", models.CharField(blank=True, max_length=5, null=True)),
                ("currency_name", models.CharField(blank=True, max_length=128, null=True)),
                ("long_name", models.CharField(max_length=255)),
                ("iso3_code", models.CharField(blank=True, max_length=3, null=True)),
                ("custom_dashboards", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
