# Generated by Django 4.1.8 on 2023-06-28 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0027_workspace"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundsreservationheader",
            options={"verbose_name": "Funds Reservation Header"},
        ),
    ]
