# Generated by Django 4.1.8 on 2023-06-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0027_workspace"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundsreservationheader",
            options={"verbose_name": "Funds Reservation Header"},
        ),
        migrations.AddField(
            model_name="intervention",
            name="has_unfunded_cash",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="total_unfunded",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="interventionactivity",
            name="activity_unfunded_cash",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="interventionactivity",
            name="unfunded_cash",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="interventionbudget",
            name="budget_total_unfunded",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="interventionbudget",
            name="has_unfunded_cash",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interventionbudget",
            name="total_unfunded",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="interventionbylocation",
            name="has_unfunded_cash",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="interventionbylocation",
            name="total_unfunded",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="interventionmanagementbudget",
            name="act1_unfunded",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="interventionmanagementbudget",
            name="act2_unfunded",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="interventionmanagementbudget",
            name="act3_unfunded",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="interventionmanagementbudget",
            name="unfunded_cash",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="document_type",
            field=models.CharField(
                choices=[("PD", "Programme Document"), ("SPD", "Simplified Programme Document")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interventionbudget",
            name="document_type",
            field=models.CharField(
                choices=[("PD", "Programme Document"), ("SPD", "Simplified Programme Document")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interventionbylocation",
            name="document_type",
            field=models.CharField(
                choices=[("PD", "Programme Document"), ("SPD", "Simplified Programme Document")],
                max_length=255,
                null=True,
            ),
        ),
    ]
