# Generated by Django 4.2.3 on 2023-09-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0027_workspace"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundsreservationheader",
            options={"verbose_name": "Funds Reservation Header"},
        ),
        migrations.AlterField(
            model_name="etoolsuser",
            name="vendor_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="document_type",
            field=models.CharField(
                choices=[("PD", "Programme Document"), ("SPD", "Simplified Programme Document")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interventionbudget",
            name="document_type",
            field=models.CharField(
                choices=[("PD", "Programme Document"), ("SPD", "Simplified Programme Document")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interventionbylocation",
            name="document_type",
            field=models.CharField(
                choices=[("PD", "Programme Document"), ("SPD", "Simplified Programme Document")],
                max_length=255,
                null=True,
            ),
        ),
    ]
