# Generated by Django 4.2.13 on 2024-07-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0028_alter_fundsreservationheader_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdindicator",
            name="section_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
