# Generated by Django 4.1.8 on 2023-07-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0028_alter_fundsreservationheader_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etoolsuser",
            name="vendor_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
