# Generated by Django 2.2 on 2019-05-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20190528_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstaffmember',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
