# Generated by Django 4.2.13 on 2024-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0029_alter_pdindicator_section_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdindicator",
            name="baseline_denominator",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="pdindicator",
            name="baseline_numerator",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="pdindicator",
            name="target_denominator",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name="pdindicator",
            name="target_numerator",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True),
        ),
    ]
