# Generated by Django 2.2 on 2019-06-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20190531_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstaffmember',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
