# Generated by Django 4.2.13 on 2024-08-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0030_alter_pdindicator_baseline_denominator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditspecial",
            name="amount_refunded",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="auditspecial",
            name="audited_expenditure",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="Audited Expenditure $"
            ),
        ),
        migrations.AddField(
            model_name="auditspecial",
            name="financial_findings",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="Financial Findings $"
            ),
        ),
        migrations.AddField(
            model_name="auditspecial",
            name="justification_provided_and_accepted",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="auditspecial",
            name="pending_unsupported_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="auditspecial",
            name="write_off_required",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="Impairment"
            ),
        ),
    ]
