# Generated by Django 2.2.2 on 2019-06-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_intervention_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionbudget',
            name='fr_numbers',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='fr_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
