# Generated by Django 2.2.2 on 2019-06-24 08:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_intervention_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionbudget',
            name='fr_numbers_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
