# Generated by Django 2.2.2 on 2019-07-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_tpm_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmactivity',
            name='created',
        ),
    ]
