# Generated by Django 2.2.3 on 2019-07-11 06:37

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_tpm_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('additional_note', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_cost_travel_agencies', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('approved_cost_traveler', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_note', models.TextField(blank=True, null=True)),
                ('certification_note', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cp_output', models.CharField(blank=True, max_length=300, null=True)),
                ('cp_output_id', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('estimated_travel_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('first_submission_date', models.DateTimeField(blank=True, null=True)),
                ('hact_visit_report', models.CharField(blank=True, max_length=300, null=True)),
                ('hidden', models.BooleanField(blank=True, null=True)),
                ('international_travel', models.NullBooleanField()),
                ('is_driver', models.BooleanField(blank=True, null=True)),
                ('is_second_traveler', models.CharField(blank=True, max_length=300, null=True)),
                ('locations', models.TextField(blank=True, null=True)),
                ('locations_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('misc_expenses', models.TextField(blank=True, null=True)),
                ('mode_of_travel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat'), ('Rail', 'Rail')], max_length=5), blank=True, null=True, size=None, verbose_name='Mode of Travel')),
                ('office_name', models.CharField(blank=True, max_length=300, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=300, null=True)),
                ('pd_ssfa_reference_number', models.CharField(blank=True, max_length=300, null=True)),
                ('pd_ssfa_title', models.CharField(blank=True, max_length=300, null=True)),
                ('preserved_expenses_local', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('preserved_expenses_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('primary_traveler', models.CharField(blank=True, max_length=300, null=True)),
                ('purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=12, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('report_note', models.TextField(blank=True, null=True)),
                ('section_name', models.CharField(blank=True, max_length=300, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_email', models.CharField(blank=True, max_length=300, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=300, null=True)),
                ('ta_required', models.NullBooleanField()),
                ('traveler_email', models.CharField(blank=True, max_length=300, null=True)),
                ('traveler_name', models.CharField(blank=True, max_length=300, null=True)),
                ('trip_attachments', models.TextField(blank=True, null=True)),
                ('trip_activity_date', models.DateField(blank=True, null=True)),
                ('trip_activity_type', models.CharField(blank=True, max_length=300, null=True)),
                ('trip_activity_reference_number', models.CharField(blank=True, max_length=300, null=True)),
                ('trip_url', models.CharField(blank=True, max_length=300, null=True)),
                ('vendor_number', models.CharField(blank=True, max_length=300, null=True)),
                ('source_activity_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
