# Generated by Django 2.2.3 on 2019-07-13 17:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_t2f_trips_cp_output_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HACTHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=300, null=True)),
                ('partner_source_id', models.IntegerField(blank=True, null=True)),
                ('vendor_number', models.CharField(blank=True, max_length=300, null=True)),
                ('partner_type', models.CharField(blank=True, max_length=300, null=True)),
                ('shared_ip', models.CharField(blank=True, max_length=300, null=True)),
                ('assessment_type', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('ct_1oct_30sep', models.CharField(blank=True, max_length=300, null=True)),
                ('liqu_1oct_30sep', models.CharField(blank=True, max_length=300, null=True)),
                ('ct_jan_dec', models.CharField(blank=True, max_length=300, null=True)),
                ('risk_rating', models.CharField(blank=True, max_length=300, null=True)),
                ('expiring_threshold', models.BooleanField(blank=True, null=True)),
                ('approach_threshold', models.BooleanField(blank=True, null=True)),
                ('pv_planned_year', models.CharField(blank=True, max_length=300, null=True)),
                ('pv_planned_q1', models.CharField(blank=True, max_length=300, null=True)),
                ('pv_planned_q2', models.CharField(blank=True, max_length=300, null=True)),
                ('pv_planned_q3', models.CharField(blank=True, max_length=300, null=True)),
                ('pv_planned_q4', models.CharField(blank=True, max_length=300, null=True)),
                ('pv_mr', models.CharField(blank=True, max_length=300, null=True)),
                ('pv_completed_year', models.CharField(blank=True, max_length=300, null=True)),
                ('pv_completed_q1', models.CharField(blank=True, max_length=300, null=True)),
                ('pv_completed_q2', models.CharField(blank=True, max_length=300, null=True)),
                ('pv_completed_q3', models.CharField(blank=True, max_length=300, null=True)),
                ('pv_completed_q4', models.CharField(blank=True, max_length=300, null=True)),
                ('sc_planned_year', models.CharField(blank=True, max_length=300, null=True)),
                ('sc_planned_q1', models.CharField(blank=True, max_length=300, null=True)),
                ('sc_planned_q2', models.CharField(blank=True, max_length=300, null=True)),
                ('sc_planned_q3', models.CharField(blank=True, max_length=300, null=True)),
                ('sc_planned_q4', models.CharField(blank=True, max_length=300, null=True)),
                ('sc_mr', models.CharField(blank=True, max_length=300, null=True)),
                ('sc_follow_up', models.BooleanField(blank=True, null=True)),
                ('sc_completed_year', models.CharField(blank=True, max_length=300, null=True)),
                ('sc_completed_q1', models.CharField(blank=True, max_length=300, null=True)),
                ('sc_completed_q2', models.CharField(blank=True, max_length=300, null=True)),
                ('sc_completed_q3', models.CharField(blank=True, max_length=300, null=True)),
                ('sc_completed_q4', models.CharField(blank=True, max_length=300, null=True)),
                ('audits_mr', models.CharField(blank=True, max_length=300, null=True)),
                ('audits_completed', models.CharField(blank=True, max_length=300, null=True)),
                ('audits_outstanding_findings', models.CharField(blank=True, max_length=300, null=True)),
                ('source_history', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('source_partner', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'HACT Detail',
                'verbose_name_plural': 'HACT Details',
                'ordering': ('year', 'country_name'),
                'unique_together': {('partner_source_id', 'year', 'country_name')},
            },
        ),
        migrations.DeleteModel(
            name='HACTDetail',
        ),
    ]
