# Generated by Django 2.2.3 on 2019-07-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_hact_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsreservation',
            name='completed_flag',
            field=models.BooleanField(default=False),
        ),
    ]
