# Generated by Django 2.2.3 on 2019-07-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_funds_fundsrereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsreservation',
            name='intervention_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
