# Generated by Django 2.2.3 on 2019-07-15 07:04

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_funds_fundsrereservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('locations', models.TextField(blank=True, null=True)),
                ('locations_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('baseline_denominator', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('baseline_numerator', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('cluster_indicator_id', models.PositiveIntegerField(blank=True, null=True)),
                ('cluster_indicator_title', models.CharField(blank=True, max_length=1024, null=True)),
                ('cluster_name', models.CharField(blank=True, max_length=512, null=True)),
                ('cp_output_name', models.TextField(blank=True, null=True)),
                ('cp_output_type', models.CharField(blank=True, max_length=150, null=True)),
                ('denominator_label', models.CharField(blank=True, max_length=256, null=True)),
                ('disaggregations', models.TextField(blank=True, null=True)),
                ('disaggregations_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('display_type', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_high_frequency', models.BooleanField(blank=True, default=False, null=True)),
                ('label', models.TextField(blank=True, max_length=4048, null=True)),
                ('lower_result_name', models.CharField(blank=True, max_length=500, null=True)),
                ('means_of_verification', models.CharField(blank=True, max_length=255, null=True)),
                ('measurement_specifications', models.TextField(blank=True, max_length=4048, null=True)),
                ('numerator_label', models.CharField(blank=True, max_length=256, null=True)),
                ('pd_output_indicator_last_modify_date', models.DateField(blank=True, null=True)),
                ('pd_output_indicator_title', models.CharField(blank=True, max_length=256, null=True)),
                ('pd_output_name', models.CharField(blank=True, max_length=256, null=True)),
                ('pd_output_section', models.CharField(blank=True, max_length=256, null=True)),
                ('pd_sffa_reference_number', models.CharField(blank=True, max_length=256, null=True)),
                ('response_plan_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('result_link_intervention', models.IntegerField(blank=True, null=True)),
                ('section_name', models.CharField(blank=True, max_length=45, null=True)),
                ('target', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('target_denominator', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('target_numerator', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Location'),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Location'),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Location'),
        ),
        migrations.AddField(
            model_name='travelactivity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Location'),
        ),
    ]
