# Generated by Django 2.2.3 on 2019-07-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_tpm_tpmvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='partner_signatory_email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='partner_signatory_first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='partner_signatory_last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_signatory_email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_signatory_first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_signatory_last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='partner_signatory_email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='partner_signatory_first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='partner_signatory_last_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
