# Generated by Django 2.2.3 on 2019-07-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.GatewayType'),
        ),
    ]
