# Generated by Django 2.2.3 on 2019-07-22 05:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportindicator',
            name='pd_output_indicator_last_modify_date',
        ),
        migrations.RemoveField(
            model_name='reportindicator',
            name='pd_output_indicator_title',
        ),
        migrations.RemoveField(
            model_name='reportindicator',
            name='pd_output_name',
        ),
        migrations.RemoveField(
            model_name='reportindicator',
            name='pd_output_section',
        ),
        migrations.AddField(
            model_name='reportindicator',
            name='assumptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportindicator',
            name='baseline',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='reportindicator',
            name='context_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportindicator',
            name='pd_outputs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportindicator',
            name='pd_outputs_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
