# Generated by Django 2.2.3 on 2019-07-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_tpm_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmvisit',
            name='visit_url',
        ),
    ]
