# Generated by Django 2.2.3 on 2019-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_reportindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportindicator',
            name='baseline_denominator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='baseline_numerator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='target_denominator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='target_numerator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
