# Generated by Django 2.2.3 on 2019-07-29 14:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='hact_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
