# Generated by Django 2.2.3 on 2019-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0066_partnemr'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='partner_source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
