# Generated by Django 2.2.3 on 2019-08-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0072_Engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='modified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
