# Generated by Django 2.2.3 on 2019-08-02 13:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0073_Engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='shared_ip_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, default=list, null=True, size=None, verbose_name='Shared Audit with'),
        ),
    ]
