# Generated by Django 2.2.4 on 2019-08-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0077_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmvisit',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
