# Generated by Django 2.2.4 on 2019-08-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0079_TravelActivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
