# Generated by Django 2.2.4 on 2019-08-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0080_Travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundsreservation',
            name='intervention',
        ),
        migrations.AddField(
            model_name='fundsreservation',
            name='delegated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fundsreservation',
            name='completed_flag',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
