# Generated by Django 2.2.4 on 2019-08-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0081_FundsReservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsreservation',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='data.Intervention'),
        ),
    ]
