# Generated by Django 2.2.4 on 2019-08-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0082_FundsReservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmvisit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='location_level',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='location_levelname',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='location_pcode',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='location_source_id',
        ),
    ]
