# Generated by Django 2.2.4 on 2019-08-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data', '0083_tpmvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(db_index=True, max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('agreement_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.CharField(blank=True, max_length=50, null=True)),
                ('file_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('filename', models.CharField(blank=True, max_length=1024, null=True)),
                ('object_link', models.CharField(blank=True, max_length=200, null=True)),
                ('partner', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_type', models.CharField(blank=True, max_length=150, null=True)),
                ('pd_ssfa', models.IntegerField(blank=True, null=True)),
                ('pd_ssfa_number', models.CharField(blank=True, max_length=64, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('vendor_number', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.CharField(blank=True, max_length=1024, null=True)),
                ('hyperlink', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UnicefAttachmentsAttachment_content_type', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
