# Generated by Django 2.2.4 on 2019-08-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0084_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='ct',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
