# Generated by Django 2.2.4 on 2019-08-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0087_auto_20190826_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdindicator',
            name='target_denominator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pdindicator',
            name='target_numerator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
