# Generated by Django 2.2.5 on 2019-09-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0090_auto_20190904_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='reference_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
