# Generated by Django 2.2.5 on 2019-09-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0092_auto_20190916_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ('country_name', 'title', 'id'), 'verbose_name': 'Intervention'},
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('schema_name', 'source_id', 'source_activity_id')},
        ),
    ]
