# Generated by Django 2.2.5 on 2019-09-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0093_auto_20190917_0603'),
    ]

    operations = [
    ]
