# Generated by Django 2.2.5 on 2019-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0097_auto_20190927_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportindicator',
            name='target_denominator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='target_numerator',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
