# Generated by Django 2.2.5 on 2019-10-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0098_auto_20191001_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpoint',
            name='location_levelname',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='location_levelname',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pdindicator',
            name='location_levelname',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='travelactivity',
            name='location_levelname',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
