# Generated by Django 2.2.5 on 2019-10-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0100_auto_20191007_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('vendor', models.CharField(blank=True, max_length=300, null=True)),
                ('partner_type', models.CharField(blank=True, max_length=300, null=True)),
                ('risk_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('audited_expenditure', models.DecimalField(decimal_places=2, max_digits=20)),
                ('financial_findings', models.DecimalField(decimal_places=2, max_digits=20)),
                ('audit_opinion', models.CharField(max_length=20)),
                ('count_high_risk_findings', models.IntegerField(blank=True, null=True)),
                ('count_financial_findings', models.IntegerField(blank=True, null=True)),
                ('count_key_control_weaknesses', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='auditresult',
            index=models.Index(fields=['source_id', 'schema_name'], name='data_auditr_source__b2a237_idx'),
        ),
    ]
