# Generated by Django 2.2.5 on 2019-10-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0101_auto_20191013_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmpindicators',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='pmpindicators',
            name='intervention_link',
        ),
        migrations.RemoveField(
            model_name='pmpindicators',
            name='partner_link',
        ),
    ]
