# Generated by Django 2.2.5 on 2019-10-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0102_auto_20191016_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
