# Generated by Django 2.2.5 on 2019-10-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0103_auditresult_vendor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmactivity',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
