# Generated by Django 2.2.6 on 2019-10-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0107_famindicator_audit_field_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famindicator',
            name='audit_field_visit',
        ),
        migrations.RemoveField(
            model_name='famindicator',
            name='spotcheck_comments_received_from_ip',
        ),
        migrations.RemoveField(
            model_name='famindicator',
            name='spotcheck_comments_received_from_unicef',
        ),
        migrations.RemoveField(
            model_name='famindicator',
            name='spotcheck_draft_report_issued_to_ip',
        ),
        migrations.RemoveField(
            model_name='famindicator',
            name='spotcheck_draft_report_issued_to_unicef',
        ),
        migrations.RemoveField(
            model_name='famindicator',
            name='spotcheck_field_visit',
        ),
    ]
