# Generated by Django 2.2.7 on 2019-12-05 13:10

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0108_auto_20191021_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('active_pd', models.TextField(blank=True, null=True)),
                ('active_pd_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('additional_supporting_documentation_provided', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('agreement', models.CharField(blank=True, max_length=300, null=True)),
                ('amount_refunded', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('authorized_officers', models.TextField(blank=True, null=True)),
                ('authorized_officers_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('cancel_comment', models.TextField(blank=True, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('date_of_cancel', models.DateField(blank=True, null=True)),
                ('date_of_comments_by_ip', models.DateField(blank=True, null=True)),
                ('date_of_comments_by_unicef', models.DateField(blank=True, null=True)),
                ('date_of_draft_report_to_ip', models.DateField(blank=True, null=True)),
                ('date_of_draft_report_to_unicef', models.DateField(blank=True, null=True)),
                ('date_of_field_visit', models.DateField(blank=True, null=True)),
                ('date_of_final_report', models.DateField(blank=True, null=True)),
                ('date_of_report_submit', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('engagement_attachments', models.TextField(blank=True, null=True)),
                ('engagement_type', models.CharField(blank=True, choices=[('sc', 'Spot Check')], db_index=True, max_length=300, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('explanation_for_additional_information', models.TextField(blank=True, null=True)),
                ('joint_audit', models.BooleanField(blank=True, default=False, null=True)),
                ('justification_provided_and_accepted', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('partner_contacted_at', models.DateField(blank=True, db_index=True, null=True)),
                ('partner', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('po_item', models.IntegerField(blank=True, null=True)),
                ('report_attachments', models.TextField(blank=True, null=True)),
                ('staff_members', models.TextField(blank=True, null=True)),
                ('staff_members_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('partner_contacted', 'IP Contacted'), ('field_visit', 'Field Visit'), ('draft_issued_to_partner', 'Draft Report Issued to IP'), ('comments_received_by_partner', 'Comments Received from IP'), ('draft_issued_to_unicef', 'Draft Report Issued to UNICEF'), ('comments_received_by_unicef', 'Comments Received from UNICEF'), ('report_submitted', 'Report Submitted'), ('final', 'Final Report'), ('cancelled', 'Cancelled')], db_index=True, max_length=30, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('write_off_required', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=300, null=True)),
                ('final_report', models.CharField(blank=True, max_length=300, null=True)),
                ('shared_ip_with', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, default=list, null=True, size=None, verbose_name='Shared Audit with')),
                ('spotcheck_total_amount_tested', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('spotcheck_total_amount_of_ineligible_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('spotcheck_internal_controls', models.TextField(blank=True, null=True)),
                ('spotcheck_final_report', models.CharField(blank=True, max_length=300, null=True)),
                ('audited_expenditure', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('financial_findings', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('audit_opinion', models.CharField(blank=True, choices=[('unqualified', 'Unqualified'), ('qualified', 'Qualified'), ('disclaimer_opinion', 'Disclaimer opinion'), ('adverse_opinion', 'Adverse opinion')], db_index=True, max_length=20, null=True)),
                ('finding_id', models.IntegerField(blank=True, null=True)),
                ('category_of_observation', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline_of_action', models.DateField(blank=True, null=True)),
                ('finding_priority', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='spotcheck',
            index=models.Index(fields=['source_id', 'schema_name'], name='data_spotch_source__df02d3_idx'),
        ),
    ]
