# Generated by Django 2.2.9 on 2020-02-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0110_auto_20191223_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='partner_signatory_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='partner_signatory_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='partner_signatory_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
