# Generated by Django 2.2.11 on 2020-04-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0111_auto_20200221_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='zonal_chief_email',
        ),
        migrations.RemoveField(
            model_name='office',
            name='zonal_chief_source_id',
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['source_id', 'schema_name'], name='data_office_source__8f99bd_idx'),
        ),
    ]
