# Generated by Django 2.2.9 on 2020-04-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0112_auto_20200406_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionpoint',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='auditresult',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='engagement',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='etoolsuser',
            options={'ordering': ('email',)},
        ),
        migrations.AlterModelOptions(
            name='interventionbudget',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='spotcheck',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='tpmvisit',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveIndex(
            model_name='attachment',
            name='data_attach_source__529f94_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditresult',
            name='data_auditr_source__b2a237_idx',
        ),
        migrations.RemoveIndex(
            model_name='engagement',
            name='data_engage_source__85fc81_idx',
        ),
        migrations.RemoveIndex(
            model_name='spotcheck',
            name='data_spotch_source__df02d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='tpmvisit',
            name='data_tpmvis_source__90b361_idx',
        ),
    ]
