# Generated by Django 2.2.9 on 2020-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0113_auto_20200408_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
