# Generated by Django 2.2.9 on 2020-04-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0113_auto_20200408_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdindicator',
            name='pd_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
