# Generated by Django 2.2.9 on 2020-04-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0116_auto_20200417_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geoname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.GeoName'),
        ),
    ]
