# Generated by Django 2.2.11 on 2020-05-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0117_auto_20200421_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsreservation',
            name='pd_reference_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
