# Generated by Django 2.2.9 on 2020-04-22 12:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0117_auto_20200421_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='auditor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='action_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
