# Generated by Django 2.2.11 on 2020-06-04 17:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0119_engagement_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='rating_extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
