# Generated by Django 2.2.11 on 2020-06-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0120_auto_20200604_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='rating',
            field=models.CharField(blank=True, choices=[(0, 'N/A'), (1, 'Low'), (2, 'Medium'), (3, 'Significant'), (4, 'High')], max_length=100, null=True),
        ),
    ]
