# Generated by Django 2.2.11 on 2020-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0121_auto_20200610_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdindicator',
            name='pd_reference_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
