# Generated by Django 2.2.11 on 2020-07-28 19:17

from django.db import migrations


def update_area_code(apps, schema_editor):
    Location = apps.get_model("data.location")
    for loc in Location.objects.filter(name="Bulgaria", area_code="057"):
        loc.area_code = "0570"
        loc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0122_pdindicator_pd_reference_number'),
    ]

    operations = [
        migrations.RunPython(
            update_area_code,
            reverse_code=migrations.RunPython.noop,
        )
    ]
