# Generated by Django 2.2.11 on 2020-07-28 19:29

from django.db import migrations


def set_location_geoname(apps, schema_editor):
    Location = apps.get_model("data.location")
    GeoName = apps.get_model("data.geoname")
    for loc in Location.objects.filter(
            geoname__isnull=True,
            latitude__isnull=False,
            longitude__isnull=False,
    ):
        geoname, __ = GeoName.objects.get_or_create(
                lat=loc.latitude,
                lng=loc.longitude,
            )
        loc.geoname = geoname
        loc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0122_pdindicator_pd_reference_number'),
    ]

    operations = [
        migrations.RunPython(
            set_location_geoname,
            reverse_code=migrations.RunPython.noop,
        )
    ]
