# Generated by Django 2.2.11 on 2020-07-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0122_pdindicator_pd_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionbylocation',
            name='p_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
