# Generated by Django 2.2.11 on 2020-08-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0122_pdindicator_pd_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='budget_currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
