# Generated by Django 2.2.11 on 2020-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0124_fmontrack_fmquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='cfei_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='cfei_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='cfei_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
