# Generated by Django 2.2.11 on 2020-09-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0125_auto_20200924_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='partner_sea_risk_rating',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='partner_sea_risk_rating',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interventionbylocation',
            name='partner_sea_risk_rating',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='sea_risk_rating_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
