# Generated by Django 2.2.11 on 2020-11-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0126_auto_20200924_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerstaffmember',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
