# Generated by Django 2.2.11 on 2020-12-01 20:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0129_auto_20201125_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotCheckFindings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('auditor', models.CharField(blank=True, max_length=255, null=True)),
                ('engagement_type', models.CharField(blank=True, choices=[('sc', 'Spot Check')], db_index=True, max_length=300, null=True)),
                ('date_of_final_report', models.DateField(blank=True, null=True)),
                ('high_priorty_findings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('low_priorty_findings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('partner', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('sections', models.TextField(blank=True, null=True)),
                ('sections_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('spotcheck_total_amount_tested', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('spotcheck_total_amount_of_ineligible_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
