# Generated by Django 2.2.11 on 2020-12-09 20:56

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0130_spotcheckfindings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('engagement_type', models.CharField(blank=True, choices=[('ma', 'Micro Assessment')], db_index=True, max_length=300, null=True)),
                ('agreement', models.CharField(blank=True, max_length=300, null=True)),
                ('partner', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('date_of_field_visit', models.DateField(blank=True, null=True)),
                ('date_of_final_report', models.DateField(blank=True, null=True)),
                ('shared_ip_with', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, default=list, null=True, size=None, verbose_name='Shared Audit with')),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('test_subject_areas', models.CharField(blank=True, max_length=50, null=True)),
                ('test_subject_areas_extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
