# Generated by Django 2.2.11 on 2020-12-16 19:15

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0131_microassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('engagement_type', models.CharField(blank=True, choices=[('audit', 'Audit')], db_index=True, max_length=300, null=True)),
                ('agreement', models.CharField(blank=True, max_length=300, null=True)),
                ('auditor', models.CharField(blank=True, max_length=255, null=True)),
                ('shared_ip_with', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, default=list, null=True, size=None, verbose_name='Shared Audit with')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_of_final_report', models.DateField(blank=True, null=True)),
                ('audited_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Audited Expenditure $')),
                ('audited_expenditure_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Audited Expenditure Local Currency')),
                ('financial_findings', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Financial Findings $')),
                ('financial_findings_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Financial Findings Local Currency')),
                ('audit_opinion', models.CharField(blank=True, max_length=254, null=True)),
                ('financial_findings_count', models.IntegerField(blank=True, null=True)),
                ('financial_findings_titles', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('key_internal_control_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
