# Generated by Django 2.2.11 on 2020-12-17 17:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0132_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('engagement_type', models.CharField(blank=True, choices=[('sa', 'Special Audit')], db_index=True, max_length=300, null=True)),
                ('agreement', models.CharField(blank=True, max_length=300, null=True)),
                ('auditor', models.CharField(blank=True, max_length=255, null=True)),
                ('shared_ip_with', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, default=list, null=True, size=None, verbose_name='Shared Audit with')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_of_final_report', models.DateField(blank=True, null=True)),
                ('joint_audit', models.BooleanField(blank=True, null=True)),
                ('date_of_field_visit', models.DateField(blank=True, null=True)),
                ('date_of_draft_report_to_ip', models.DateField(blank=True, null=True)),
                ('date_of_comments_by_ip', models.DateField(blank=True, null=True)),
                ('date_of_draft_report_to_unicef', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
