# Generated by Django 2.2.17 on 2021-01-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0134_auto_20210105_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microassessment',
            name='subject_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microassessment',
            name='test_subject_areas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
