# Generated by Django 2.2.17 on 2021-01-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0134_auto_20210105_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='financial_findings_titles',
        ),
        migrations.RemoveField(
            model_name='microassessment',
            name='test_subject_areas',
        ),
    ]
