# Generated by Django 2.2.17 on 2021-01-26 02:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0135_auto_20210121_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotcheckfindings',
            old_name='high_priorty_findings',
            new_name='high_priority_findings',
        ),
        migrations.RenameField(
            model_name='spotcheckfindings',
            old_name='low_priorty_findings',
            new_name='low_priority_findings',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='financial_findings_titles',
        ),
        migrations.AddField(
            model_name='audit',
            name='action_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='action_points_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='amount_refunded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='financial_findings_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='financial_findings_by_category',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='justification_provided_and_accepted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='key_internal_control_by_category',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='offices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='offices_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='pending_unsupported_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='percent_of_audited_expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='sections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='sections_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='test_subject_areas_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='write_off_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Impairment'),
        ),
        migrations.AddField(
            model_name='auditspecial',
            name='action_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='auditspecial',
            name='action_points_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='auditspecial',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditspecial',
            name='offices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditspecial',
            name='offices_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='auditspecial',
            name='sections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditspecial',
            name='sections_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='auditspecial',
            name='special_procedures_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='accounting_policies_and_procedures_risk_rating',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='action_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='action_points_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='financial_reporting_and_monitoring_risk_rating',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='findings_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='fixed_assets_and_inventory_risk_rating',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='implementing_partner_risk_rating',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='organizational_structure_and_staffing_risk_rating',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='overall_risk_rating',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='procurement_and_contract_administration_risk_rating',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='programme_management_risk_rating',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='test_subject_areas_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotcheckfindings',
            name='action_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='spotcheckfindings',
            name='action_points_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='spotcheckfindings',
            name='additional_supporting_documentation_provided',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='spotcheckfindings',
            name='amount_refunded',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='spotcheckfindings',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotcheckfindings',
            name='justification_provided_and_accepted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='spotcheckfindings',
            name='pending_unsupported_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='spotcheckfindings',
            name='write_off_required',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='audited_expenditure_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='financial_findings_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
