# Generated by Django 2.2.15 on 2021-02-03 20:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0136_auto_20210126_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='action_points_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='engagement_type',
            field=models.CharField(blank=True, choices=[('audit', 'Audit'), ('ma', 'Micro Assessment'), ('sc', 'Spot Check'), ('sa', 'Special Audit')], db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='auditspecial',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditspecial',
            name='engagement_type',
            field=models.CharField(blank=True, choices=[('audit', 'Audit'), ('ma', 'Micro Assessment'), ('sc', 'Spot Check'), ('sa', 'Special Audit')], db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='action_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microassessment',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microassessment',
            name='engagement_type',
            field=models.CharField(blank=True, choices=[('audit', 'Audit'), ('ma', 'Micro Assessment'), ('sc', 'Spot Check'), ('sa', 'Special Audit')], db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheckfindings',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheckfindings',
            name='engagement_type',
            field=models.CharField(blank=True, choices=[('audit', 'Audit'), ('ma', 'Micro Assessment'), ('sc', 'Spot Check'), ('sa', 'Special Audit')], db_index=True, max_length=300, null=True),
        ),
    ]
