# Generated by Django 3.1.6 on 2021-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0137_auto_20210210_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='action_points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='action_points_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='financial_findings_by_category',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='key_internal_control_by_category',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='offices_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='partner',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='sections_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='auditspecial',
            name='action_points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='auditspecial',
            name='action_points_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='auditspecial',
            name='offices_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='auditspecial',
            name='partner',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='auditspecial',
            name='sections_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='action_points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='active_pd_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='authorized_officers_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='partner',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='rating_extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='staff_members_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fmquestion',
            name='answer',
            field=models.JSONField(blank=True, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='fmquestion',
            name='summary_answer',
            field=models.JSONField(blank=True, null=True, verbose_name='Summary Answer'),
        ),
        migrations.AlterField(
            model_name='hacthistory',
            name='source_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hacthistory',
            name='source_partner',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='contingency_pd',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='cp_outputs_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='locations_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='offices_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='partner_focal_points_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='sections_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='unicef_focal_points_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='contingency_pd',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='cp_outputs_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='fr_numbers_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='locations_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='offices_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='partner_focal_points_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='sections_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='unicef_focal_points_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='contingency_pd',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='cp_outputs_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='offices_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='partner_focal_points_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='sections_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interventionbylocation',
            name='unicef_focal_points_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='microassessment',
            name='action_points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='microassessment',
            name='action_points_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='microassessment',
            name='partner',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='microassessment',
            name='rating_extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='microassessment',
            name='subject_area_extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='hact_min_requirements',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='hact_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='planned_engagement',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='baseline',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='disaggregations_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='locations_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='pd_outputs_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportindicator',
            name='target',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheck',
            name='active_pd_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheck',
            name='authorized_officers_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheck',
            name='partner',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheck',
            name='staff_members_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheckfindings',
            name='action_points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheckfindings',
            name='action_points_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheckfindings',
            name='high_priority_findings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheckfindings',
            name='low_priority_findings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheckfindings',
            name='partner',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='spotcheckfindings',
            name='sections_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='attachments_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='locations_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='offices_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='report_attachments_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='tpm_focal_points_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='activities_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='international_travel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='ta_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='international_travel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='locations_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ta_required',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
