# Generated by Django 3.1.6 on 2021-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0138_auto_20210210_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmontrack',
            name='field_office',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fmontrack',
            name='reference_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fmontrack',
            name='sections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fmontrack',
            name='sections_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='fmontrack',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fmontrack',
            name='location',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
