# Generated by Django 3.1.6 on 2021-03-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0139_auto_20210311_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='highest_risk_rating_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='highest_risk_rating_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
