# Generated by Django 3.1.6 on 2021-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0141_auto_20210311_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmontrack',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
