# Generated by Django 3.1.6 on 2021-03-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0142_auto_20210329_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotCheck',
        ),
    ]
