# Generated by Django 3.1.8 on 2021-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0143_delete_spotcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmontrack',
            name='monitoring_activity_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monitoring Activity ID'),
        ),
        migrations.AddField(
            model_name='fmquestion',
            name='monitoring_activity',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Monitoring Activity'),
        ),
    ]
