# Generated by Django 3.1.8 on 2021-05-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0144_auto_20210519_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmontrack',
            name='person_responsible_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fmontrack',
            name='team_members',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fmquestion',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fmquestion',
            name='information_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fmquestion',
            name='is_hact',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
