# Generated by Django 3.1.8 on 2021-06-11 04:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0145_auto_20210519_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
