# Generated by Django 3.1.8 on 2021-06-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0147_auto_20210611_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('option_value', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('question_id', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('is_custom', models.BooleanField(blank=True, default=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='hacthistory',
            name='source_history',
        ),
        migrations.RemoveField(
            model_name='hacthistory',
            name='source_partner',
        ),
    ]
