# Generated by Django 3.1.8 on 2021-07-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0148_auto_20210629_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmontrack',
            name='entity_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entity Type'),
        ),
        migrations.AddField(
            model_name='fmontrack',
            name='output',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Output WBS'),
        ),
        migrations.AddField(
            model_name='fmontrack',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
