# Generated by Django 3.1.8 on 2021-07-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0149_auto_20210709_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('result_type', models.CharField(blank=True, max_length=150, null=True)),
                ('section', models.CharField(blank=True, max_length=128, null=True)),
                ('gic_code', models.CharField(blank=True, max_length=8, null=True)),
                ('gic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('humanitarian_tag', models.BooleanField(blank=True, null=True)),
                ('sic_code', models.CharField(blank=True, max_length=8, null=True)),
                ('sic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wbs', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_focus_code', models.CharField(blank=True, max_length=8, null=True)),
                ('activity_focus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('ram', models.BooleanField(blank=True, null=True)),
                ('country_programme', models.CharField(blank=True, max_length=255, null=True)),
                ('humanitarian_marker_code', models.CharField(blank=True, max_length=255, null=True)),
                ('humanitarian_marker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('programme_area_code', models.CharField(blank=True, max_length=16, null=True)),
                ('programme_area_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fmontrack',
            name='programme_areas',
            field=models.TextField(blank=True, null=True, verbose_name='Programme Areas'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['source_id', 'schema_name'], name='data_result_source__f42c5d_idx'),
        ),
    ]
