# Generated by Django 3.2.6 on 2021-08-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0151_auto_20210727_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='PseaAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('assessment_partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assessment_vendor_number', models.CharField(blank=True, max_length=30, null=True)),
                ('assessment_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_status', models.CharField(blank=True, max_length=30, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('indicator_subject', models.TextField(blank=True, null=True)),
                ('indicator_content', models.TextField(blank=True, null=True)),
                ('indicator_active', models.BooleanField(blank=True, null=True)),
                ('indicator_rating_instructions', models.TextField(blank=True, null=True)),
                ('rating_label', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_active', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PseaAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_number', models.CharField(blank=True, max_length=30, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('overall_rating', models.IntegerField(blank=True, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('assessor', models.JSONField(blank=True, default=dict, null=True)),
                ('focal_points', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
