# Generated by Django 3.2.6 on 2021-08-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0152_pseaanswer_pseaassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmquestion',
            name='location',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
