# Generated by Django 3.2.6 on 2021-08-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0153_alter_fmquestion_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseaanswer',
            name='assessment_cso_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pseaassessment',
            name='cso_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
