# Generated by Django 3.2.6 on 2021-08-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0154_auto_20210809_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='lead_office',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='lead_section',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
