# Generated by Django 3.2 on 2021-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0156_auto_20210825_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='auditor_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='auditspecial',
            name='auditor_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='auditor_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='auditor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='microassessment',
            name='auditor_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='spotcheckfindings',
            name='auditor_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
