# Generated by Django 3.2.6 on 2021-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0157_auto_20210924_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='additional_supporting_documentation_provided',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='amount_refunded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='date_of_draft_report_to_ip',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='justification_provided_and_accepted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='pending_unsupported_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='write_off_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Impairment'),
        ),
    ]
