# Generated by Django 3.1.13 on 2021-11-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0158_auto_20211103_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='date_of_draft_report_to_ip',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotcheckfindings',
            name='date_of_draft_report_to_ip',
            field=models.DateField(blank=True, null=True),
        ),
    ]
