# Generated by Django 3.1.13 on 2021-11-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0159_auto_20211118_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerHact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('area_code', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('vendor_number', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_assessment', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_type', models.CharField(blank=True, choices=[('Bilateral / Multilateral', 'Bilateral / Multilateral'), ('Civil Society Organization', 'Civil Society Organization'), ('Government', 'Government'), ('UN Agency', 'UN Agency')], db_index=True, max_length=50, null=True)),
                ('cso_type', models.CharField(blank=True, choices=[('International', 'International'), ('National', 'National'), ('Community Based Organization', 'Community Based Organization'), ('Academic Institution', 'Academic Institution')], db_index=True, max_length=50, null=True)),
                ('rating', models.CharField(blank=True, choices=[('High', 'High'), ('Significant', 'Significant'), ('Medium', 'Medium'), ('Low', 'Low'), ('Not Required', 'Not Required')], db_index=True, max_length=50, null=True)),
                ('hact_values', models.JSONField(blank=True, null=True)),
                ('hact_min_requirements', models.JSONField(blank=True, default=dict, null=True)),
                ('programmatic_visits', models.JSONField(blank=True, default=dict, null=True)),
                ('spot_checks', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('schema_name', 'name', 'vendor_number'), ('schema_name', 'vendor_number')},
            },
        ),
    ]
