# Generated by Django 3.2.6 on 2021-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0160_partnerhact'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmquestion',
            name='overall_finding',
            field=models.JSONField(blank=True, null=True, verbose_name='Overall Finding'),
        ),
    ]
