# Generated by Django 3.2.6 on 2022-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0161_fmquestion_overall_finding'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='sections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='sections_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
