# Generated by Django 3.1.14 on 2022-02-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0162_auto_20220119_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='gateway',
        ),
        migrations.AddField(
            model_name='location',
            name='admin_level',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='admin_level_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
