# Generated by Django 3.2.12 on 2022-03-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0164_auto_20220311_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsreservation',
            name='line_item_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
