# Generated by Django 3.2.12 on 2022-03-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0165_alter_fundsreservation_line_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmquestion',
            name='question_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Question ID'),
        ),
    ]
