# Generated by Django 2.2.5 on 2019-09-06 13:12

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_token', models.CharField(max_length=40)),
                ('server', models.CharField(default='https://app.rapidpro.io/', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_language', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('date_style', models.CharField(blank=True, max_length=100, null=True)),
                ('credits', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('anon', models.BooleanField(default=False)),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rapidpro.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('name', models.TextField()),
                ('query', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidpro.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
