# Generated by Django 2.2.5 on 2019-09-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidpro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
