# Generated by Django 2.2.5 on 2019-10-07 08:33

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidpro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('expires', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('expired', models.IntegerField(default=0)),
                ('interrupted', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidpro.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidpro.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlowStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('restart_participants', models.NullBooleanField()),
                ('status', models.CharField(max_length=100)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('contacts', models.ManyToManyField(to='rapidpro.Contact')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rapidpro.Flow')),
                ('groups', models.ManyToManyField(to='rapidpro.Group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidpro.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='labels',
            field=models.ManyToManyField(to='rapidpro.Label'),
        ),
        migrations.AddField(
            model_name='flow',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidpro.Organization'),
        ),
        migrations.AddField(
            model_name='flow',
            name='runs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rapidpro.Runs'),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rapidpro.Group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidpro.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
