# Generated by Django 2.2.5 on 2019-09-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidpro', '0002_auto_20190906_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
