# Generated by Django 2.2.5 on 2019-10-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapidpro', '0002_auto_20191007_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='modified_on',
        ),
    ]
