# Generated by Django 2.2.5 on 2019-09-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0096_auto_20190919_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorByLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_source_id', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=254, null=True)),
                ('location_pcode', models.CharField(blank=True, max_length=32, null=True)),
                ('location_level', models.IntegerField(blank=True, null=True)),
                ('location_levelname', models.CharField(blank=True, max_length=32, null=True)),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('partner', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('indicator_target', models.CharField(blank=True, max_length=50, null=True)),
                ('indicator_baseline', models.CharField(blank=True, max_length=50, null=True)),
                ('title_of_indicator', models.TextField(blank=True, max_length=2048, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etools_datamart.apps.mart.data.Location')),
            ],
        ),
    ]
