# Generated by Django 3.2.12 on 2022-04-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('seen', models.DateTimeField(blank=True, null=True)),
                ('business_area', models.CharField(blank=True, max_length=2048, null=True)),
                ('intervention_reference_number', models.CharField(blank=True, max_length=2048, null=True)),
                ('pd_output_progress_status', models.CharField(blank=True, max_length=2048, null=True)),
                ('performance_indicator', models.CharField(blank=True, max_length=2048, null=True)),
                ('baseline', models.CharField(blank=True, max_length=2048, null=True)),
                ('target', models.CharField(blank=True, max_length=2048, null=True)),
                ('total_cumulative_progress', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
    ]
