# Generated by Django 3.2.12 on 2022-05-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0002_indicatorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='time_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='time_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
