# Generated by Django 3.2.12 on 2022-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0003_auto_20220504_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
