# Generated by Django 3.2.13 on 2022-09-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0004_indicatorreport_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreport',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='report_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorreport',
            name='report_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
