# Generated by Django 2.2.7 on 2019-12-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0004_auto_20191208_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareport',
            name='total_cummulative_progress',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
