# Generated by Django 2.2.7 on 2019-12-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0005_datareport_total_cummulative_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datareport',
            old_name='total_cummulative_progress',
            new_name='total_cumulative_progress',
        ),
        migrations.RenameField(
            model_name='datareport',
            old_name='total_cummulative_progress_in_location',
            new_name='total_cumulative_progress_in_location',
        ),
    ]
