# Generated by Django 3.2.16 on 2022-11-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0005_auto_20220903_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareport',
            name='pd_output_title',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
