# Generated by Django 2.2.9 on 2020-02-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0006_auto_20191208_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareport',
            name='achievement_in_reporting_period',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
