# Generated by Django 2.2.11 on 2020-04-02 14:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0007_datareport_achievement_in_reporting_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareport',
            name='disaggregation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
