# Generated by Django 2.2.11 on 2020-05-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0008_datareport_disaggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareport',
            name='report_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
