# Generated by Django 2.2.11 on 2020-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0009_datareport_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareport',
            name='report_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
