# Generated by Django 2.2.11 on 2020-07-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0010_datareport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareport',
            name='admin_level',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datareport',
            name='p_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
