# Generated by Django 3.1.6 on 2021-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0011_auto_20200723_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datareport',
            name='disaggregation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datareport',
            name='locations_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
