# Generated by Django 3.2 on 2021-08-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prp', '0012_auto_20210210_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datareport',
            name='pd_output_narrative_assessment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
